# -*- coding: utf-8 -*-
# Uc taramanin disinda kalmis, gercek/gorunur ek UI metinleri. Duz tirnakli
# metin degisimi (prop'tan bagimsiz) - "English" -> "Turkce" tam esleme.
import io

TR = {
 # Cursor 3.13+ ana ajan ekrani ve yeni coklu-gorev/MCP yuzeyleri
 "Plan, Build, / for skills, @ for context": "Planlayın ve oluşturun; beceriler için /, bağlam için @",
 "Plan, search, build anything": "Planlayın, arayın, istediğinizi oluşturun",
 "Ask, learn, brainstorm": "Sorun, öğrenin, fikir üretin",
 "Work on explicitly added files (no tools)": "Yalnızca eklenen dosyalarda çalışın (araç yok)",
 "Add agents, context, tools...": "Ajan, bağlam ve araç ekle...",
 "Multitask Mode": "Çoklu Görev Modu",
 "Parallelize Build with Multitask Mode.": "Çoklu Görev Modu ile oluşturma işini paralelleştirin.",
 "Coordinate parallel tasks...": "Paralel görevleri koordine edin...",
 "Orchestrate multiple subagents in parallel": "Birden fazla alt ajanı paralel olarak yönetin",
 "Search MCP servers...": "MCP sunucularında ara...",
 "Open MCP Settings": "MCP Ayarlarını Aç",
 "Import your Claude Code conversations": "Claude Code konuşmalarınızı içe aktarın",
 "Sync your chats and continue them in Cursor": "Sohbetlerinizi eşitleyin ve Cursor'da devam edin",
 "Bring over your chats, and send a follow-up to fork it. Your plugins and skills are synced by default.": "Sohbetlerinizi aktarın; devam mesajı gönderdiğinizde yeni bir dal oluşturulsun. Eklentileriniz ve becerileriniz varsayılan olarak eşitlenir.",
 # Genel eylem/durum etiketleri
 "Add MCP server": "MCP sunucusu ekle", "Add Marketplace": "Market Ekle",
 "Add agents, context, tools": "Ajanlar, bağlam, araçlar ekle",
 "Add plugin source": "Eklenti kaynağı ekle",
 "Add plugins to marketplace": "Markete eklenti ekle",
 "Add to marketplace": "Markete ekle",
 "Authenticate this plugin": "Bu eklentiyi kimlik doğrula",
 "Back": "Geri", "Cancel new folder": "Yeni klasörü iptal et",
 "Cancel recording": "Kaydı iptal et", "Canvas sharing": "Canvas paylaşımı",
 "Change action": "Eylemi değiştir", "Change pull locally action": "Yerelde çekme eylemini değiştir",
 "Changes requested": "Değişiklik istendi",
 "Classification triggered": "Sınıflandırma tetiklendi",
 "Clear selection": "Seçimi temizle", "Close": "Kapat",
 "Close fullscreen": "Tam ekranı kapat", "Close fullscreen video": "Tam ekran videoyu kapat",
 "Close toast": "Bildirimi kapat", "Composer not found": "Composer bulunamadı",
 "Confirmation input": "Onay girişi",
 "Copy error details": "Hata ayrıntılarını kopyala",
 "Cursor position": "İmleç konumu",
 "Default Off": "Varsayılan Kapalı", "Default On": "Varsayılan Açık",
 "Delete marketplace confirmation": "Market silme onayı",
 "Embedding Model": "Gömme Modeli",
 "Enable Auto Refresh": "Otomatik Yenilemeyi Etkinleştir",
 "Enable MAX Mode": "MAX Modunu Etkinleştir",
 "Environment filters": "Ortam filtreleri",
 "Expand all": "Tümünü genişlet", "Expand down": "Aşağı genişlet",
 "Expand to fullscreen": "Tam ekrana genişlet", "Expand up": "Yukarı genişlet",
 "Feedback comment": "Geri bildirim yorumu",
 "Filter by Environment": "Ortama göre filtrele", "Filter by options": "Seçeneklere göre filtrele",
 "Filter by scope": "Kapsama göre filtrele", "Filter by updated": "Güncellenmeye göre filtrele",
 "Filter SCM requests by endpoint": "SCM isteklerini uç noktaya göre filtrele",
 "First Name": "Ad", "Last Name": "Soyad",
 "For ": "Şunun için: ",
 "Forwarded Ports": "İletilen Bağlantı Noktaları", "Forwarded ports": "İletilen bağlantı noktaları",
 "From this workspace": "Bu çalışma alanından",
 "Get Editor Layout": "Düzenleyici Düzenini Al",
 "GitHub organization picker": "GitHub kuruluş seçici",
 "Go Back": "Geri Git", "Go back": "Geri git", "Go to End": "Sona Git",
 "Group by options": "Seçeneklere göre grupla", "Grouping Options": "Gruplama Seçenekleri",
 "Hide Decorations": "Süslemeleri Gizle", "Hide Deletion Zones": "Silme Bölgelerini Gizle",
 "Hide Email Address": "E-posta Adresini Gizle", "Hide Performance Bar": "Performans Çubuğunu Gizle",
 "Hide Sidebar": "Kenar Çubuğunu Gizle", "Hide tips": "İpuçlarını gizle",
 "Highlighted line": "Vurgulanan satır", "Highlighted (navigation)": "Vurgulanan (gezinme)",
 "Hover decoration": "Üzerine gelme süslemesi",
 "Internal Client Error": "Dahili İstemci Hatası",
 "Invalid file selection (missing URI)": "Geçersiz dosya seçimi (URI eksik)",
 "Invalid view filter was ignored": "Geçersiz görünüm filtresi yok sayıldı",
 "Invalid view ordering was ignored": "Geçersiz görünüm sıralaması yok sayıldı",
 "Lint error": "Lint hatası", "Loading canvas": "Canvas yükleniyor",
 "MCP impact confirmation": "MCP etki onayı",
 "Manage installed plugins": "Yüklü eklentileri yönet",
 "Maximum on-demand monthly limit": "En fazla isteğe bağlı aylık sınır",
 "Meet the new Agents Window": "Yeni Ajanlar Penceresiyle tanışın",
 "Mention preview": "Anma önizlemesi", "Message copied to clipboard": "Mesaj panoya kopyalandı",
 "Message send failed": "Mesaj gönderilemedi", "Model selection": "Model seçimi",
 "More actions": "Diğer eylemler", "More info": "Daha fazla bilgi", "More options": "Diğer seçenekler",
 "Name of the debug visualizer": "Hata ayıklama görselleştiricisinin adı",
 "Needs attention": "İlgi gerekiyor",
 "New Agents Window (Glass)": "Yeni Ajanlar Penceresi (Glass)",
 "Next image": "Sonraki görsel", "Next page": "Sonraki sayfa", "Next step": "Sonraki adım",
 "No Hidden Dialogs Yet": "Henüz Gizli İletişim Kutusu Yok",
 "No applied changes to undo": "Geri alınacak uygulanmış değişiklik yok",
 "No available options": "Kullanılabilir seçenek yok",
 "No branch or commit hash found": "Dal veya commit karması bulunamadı",
 "No changes to commit": "Commit edilecek değişiklik yok",
 "No changes to review": "İncelenecek değişiklik yok",
 "No commit has been scored yet": "Henüz puanlanmış commit yok",
 "No composer selected": "Seçili composer yok",
 "No environment.json": "environment.json yok",
 "No git worktree found for this chat": "Bu sohbet için git çalışma ağacı bulunamadı",
 "No models found": "Model bulunamadı", "No modes found": "Mod bulunamadı",
 "No request ID found": "İstek kimliği bulunamadı",
 "No request ID found for this message": "Bu mesaj için istek kimliği bulunamadı",
 "No request content available": "Kullanılabilir istek içeriği yok",
 "No secondary text": "İkincil metin yok", "No selection precursor": "Seçim öncüsü yok",
 "No upstream remote found to open PR": "PR açmak için üst akış uzağı bulunamadı",
 "No workspace folder found": "Çalışma alanı klasörü bulunamadı",
 "No workspace open to create PR from": "PR oluşturmak için açık çalışma alanı yok",
 "No worktree to open PR": "PR açmak için çalışma ağacı yok",
 "On-demand monthly limit": "İsteğe bağlı aylık sınır",
 "Open Background Agent Overview": "Arka Plan Ajanı Özetini Aç",
 "Open Composer Settings": "Composer Ayarlarını Aç", "Open Datadog Logs": "Datadog Günlüklerini Aç",
 "Open Debug Directory": "Hata Ayıklama Dizinini Aç", "Open Prompt Quality": "Prompt Quality'yi Aç",
 "Open Request Logs": "İstek Günlüklerini Aç", "Open Virtual Machine": "Sanal Makineyi Aç",
 "Open configure menu": "Yapılandırma menüsünü aç", "Open in Datadog": "Datadog'da Aç",
 "Open in Prompt Quality": "Prompt Quality'de Aç", "Open link failed": "Bağlantı açılamadı",
 "Open or Focus Agents Window (Glass)": "Ajanlar Penceresini Aç veya Odaklan (Glass)",
 "Opened GitHub compare view": "GitHub karşılaştırma görünümü açıldı",
 "Opened Glass Automations": "Glass Otomasyonları açıldı",
 "Opened pull request page": "Pull request sayfası açıldı",
 "Ordering Options": "Sıralama Seçenekleri",
 "Paste as": "Farklı yapıştır",
 "Pending import decoration": "Bekleyen içe aktarma süslemesi",
 "Potentially outdated Dockerfile": "Eski olabilecek Dockerfile",
 "Potentially outdated environment.json": "Eski olabilecek environment.json",
 "Preview Box for Terminal Cmd/Ctrl+K": "Terminal Cmd/Ctrl+K için Önizleme Kutusu",
 "Project Database Could Not Be Rendered": "Proje Veritabanı Görüntülenemedi",
 "Project database could not be validated": "Proje veritabanı doğrulanamadı",
 "Pull locally options": "Yerelde çekme seçenekleri", "Pulling locally": "Yerelde çekiliyor",
 "RPC call failed": "RPC çağrısı başarısız",
 "Referenced Dockerfile missing": "Referans verilen Dockerfile eksik",
 "Register Close Tooltip": "Kapatma İpucunu Kaydet",
 "Registers a new title variable": "Yeni bir başlık değişkeni kaydeder",
 "Remote connection state changed": "Uzak bağlantı durumu değişti",
 "Remove image": "Görseli kaldır", "Remove marketplace confirmation": "Market kaldırma onayı",
 "Remove mention": "Anmayı kaldır", "Remove staged MCP server": "Hazırlanan MCP sunucusunu kaldır",
 "Remove staged plugin": "Hazırlanan eklentiyi kaldır", "Remove video": "Videoyu kaldır",
 "Rendered rows overlap in the DOM": "Görüntülenen satırlar DOM'da çakışıyor",
 "Request ID copied to clipboard": "İstek kimliği panoya kopyalandı",
 "Request content downloaded": "İstek içeriği indirildi",
 "Reset Composer Position": "Composer Konumunu Sıfırla", "Reset to default": "Varsayılana sıfırla",
 "Resize All Heights": "Tüm Yükseklikleri Yeniden Boyutlandır",
 "Resource read failed": "Kaynak okunamadı",
 "Run Everything Mode Warning": "Her Şeyi Çalıştır Modu Uyarısı",
 "Run Everything enabled for this agent": "Bu ajan için Her Şeyi Çalıştır etkinleştirildi",
 "Run Task": "Görevi Çalıştır", "Running Capabilities": "Çalışan Yetenekler",
 "Sandbox debug logging enabled": "Korumalı alan hata ayıklama günlüğü etkin",
 "Score Commit for AI Content": "Commit'i Yapay Zeka İçeriği İçin Puanla",
 "Search failed": "Arama başarısız", "Select to End": "Sona Kadar Seç",
 "Selected on-demand monthly limit": "Seçilen isteğe bağlı aylık sınır",
 "Serve Marketplace From Cursor": "Marketi Cursor'dan Sun",
 "Show full command output": "Tam komut çıktısını göster",
 "Show hidden breadcrumb items": "Gizli içerik haritası öğelerini göster",
 "Show markdown hover participant actions": "Markdown üzerine gelme katılımcı eylemlerini göster",
 "Sort by options": "Seçeneklere göre sırala",
 "Stale snapshot from warm fork": "Sıcak çataldan eski anlık görüntü",
 "Stop generation": "Üretimi durdur",
 "Switch to Agents Window (Glass)": "Ajanlar Penceresine Geç (Glass)",
 "Task definition file": "Görev tanım dosyası",
 "The cell index": "Hücre indeksi", "The cell range": "Hücre aralığı",
 "The cell range options": "Hücre aralığı seçenekleri", "The document uri": "Belge URI'si",
 "The kernel info": "Çekirdek bilgisi", "The language for the cell": "Hücrenin dili",
 "The name of the variable to register": "Kaydedilecek değişkenin adı",
 "The position at which to start": "Başlanacak konum",
 "The schema to use for this file": "Bu dosya için kullanılacak şema",
 "The target cell language": "Hedef hücre dili",
 "The text document in which to start": "Başlanacak metin belgesi",
 "Thumbs down": "Beğenme", "Thumbs up": "Beğen",
 "Total number of streams monitored": "İzlenen toplam akış sayısı",
 "Trigger a code action": "Bir kod eylemini tetikle",
 "Try this plugin in chat": "Bu eklentiyi sohbette dene",
 "URL of the SSE-based MCP server": "SSE tabanlı MCP sunucusunun URL'si",
 "Use /in-cloud for cloud subagents": "Bulut alt ajanları için /in-cloud kullanın",
 "Variable description": "Değişken açıklaması", "View Response A": "Yanıt A'yı Görüntüle",
 "Zoom in": "Yakınlaştır", "Zoom out": "Uzaklaştır",

 # Glass'a ozgu ek metinler
 "Accepted": "Kabul edildi", "Action already enabled": "Eylem zaten etkin",
 "Active workspace references": "Etkin çalışma alanı referansları",
 "Agent environment": "Ajan ortamı",
 "Allow Agents on My PRs": "PR'larımda Ajanlara İzin Ver",
 "Always Show Error": "Hatayı Her Zaman Göster",
 "Application User Persistent Storage": "Uygulama Kullanıcısı Kalıcı Depolaması",
 "Approved": "Onaylandı",
 "Back From Automation": "Otomasyondan Geri Dön",
 "Close Observatory": "Observatory'yi Kapat", "Close Window": "Pencereyi Kapat",
 "Close action needed": "Kapatma eylemi gerekli", "Close add secrets": "Gizli diziler eklemeyi kapat",
 "Close agent list": "Ajan listesini kapat", "Close background work tray": "Arka plan iş tepsisini kapat",
 "Close diff meter": "Fark göstergesini kapat", "Close environment setup tray": "Ortam kurulum tepsisini kapat",
 "Close metrics help": "Ölçüm yardımını kapat", "Close references": "Referansları kapat",
 "Close save environment": "Ortam kaydetmeyi kapat", "Close sidebar": "Kenar çubuğunu kapat",
 "Close subagent preview": "Alt ajan önizlemesini kapat", "Close usage details": "Kullanım ayrıntılarını kapat",
 "Cmd+K inline edit attached to prompt bar": "İstem çubuğuna eklenmiş Cmd+K satır içi düzenleme",
 "Comment options": "Yorum seçenekleri",
 "Compact grouped edits and shells": "Kompakt gruplanmış düzenlemeler ve kabuklar",
 "Compact grouped tool calls": "Kompakt gruplanmış araç çağrıları",
 "Confirm Action": "Eylemi Onayla",
 "Connecting to Cloud Desktop": "Bulut Masaüstüne bağlanılıyor",
 "Continue on": "Devam et",
 "Conversation density": "Konuşma yoğunluğu", "Conversation density preview": "Konuşma yoğunluğu önizlemesi",
 "Created by Evan You": "Evan You tarafından oluşturuldu",
 "Created by Guido van Rossum": "Guido van Rossum tarafından oluşturuldu",
 "Created by Linus Torvalds": "Linus Torvalds tarafından oluşturuldu",
 "Created by Mozilla Research": "Mozilla Research tarafından oluşturuldu",
 "Cursor Private Inference is available": "Cursor Özel Çıkarımı kullanılabilir",
 "Delete All Data": "Tüm Verileri Sil", "Destructive Action": "Yıkıcı Eylem",
 "Developed by Facebook": "Facebook tarafından geliştirildi",
 "Developed by Google": "Google tarafından geliştirildi",
 "Developed by Microsoft": "Microsoft tarafından geliştirildi",
 "Diff selection actions": "Fark seçim eylemleri",
 "Diff with hidden decorations": "Gizli süslemelerle fark",
 "Discard All Changes": "Tüm Değişiklikleri At",
 "Dismiss cloud setup promotion": "Bulut kurulum tanıtımını kapat",
 "Dismiss error": "Hatayı kapat", "Dismiss local agent interruption": "Yerel ajan kesintisini kapat",
 "Dismiss notification": "Bildirimi kapat",
 "Edits with diffs and compact shells": "Farklı düzenlemeler ve kompakt kabuklar",
 "Environment save scope": "Ortam kaydetme kapsamı",
 "Files to exclude": "Dışlanacak dosyalar", "Files to include": "Dahil edilecek dosyalar",
 "First choice": "İlk seçenek",
 "Font Smoothing": "Yazı Tipi Yumuşatma",
 "Frontend React Application": "Ön Uç React Uygulaması",
 "Global storage across entire application": "Tüm uygulama genelinde genel depolama",
 "GitHub App No Access": "GitHub Uygulamasının Erişimi Yok",
 "New Agent": "Yeni Ajan", "New File": "Yeni Dosya", "New Folder": "Yeni Klasör",
 "New PR Options": "Yeni PR Seçenekleri", "New Project": "Yeni Proje",
 "New folder": "Yeni klasör", "New folder name": "Yeni klasör adı",
 "New secret value": "Yeni gizli değer", "New session": "Yeni oturum",
 "New tab options": "Yeni sekme seçenekleri",
 "Next Chat (Direct)": "Sonraki Sohbet (Doğrudan)", "Next Palette Filter": "Sonraki Palet Filtresi",
 "No Icon": "Simge Yok",
 "No changes": "Değişiklik yok",
 "No connection service": "Bağlantı hizmeti yok", "No context files": "Bağlam dosyası yok",
 "No description": "Açıklama yok", "No lifecycle service": "Yaşam döngüsü hizmeti yok",
 "No owner recorded": "Kayıtlı sahip yok",
 "No signals to show": "Gösterilecek sinyal yok", "No subscriptions yet": "Henüz abonelik yok",
 "Normal - Selected": "Normal - Seçili", "Normal - Unselected": "Normal - Seçili Değil",
 "Open (fade)": "Aç (solma)", "Open (scale)": "Aç (ölçek)",
 "Open Agent by ID": "Kimliğe Göre Ajan Aç", "Open Cloud Agent View by ID": "Kimliğe Göre Bulut Ajanı Görünümünü Aç",
 "Open Cloud Agent by ID": "Kimliğe Göre Bulut Ajanı Aç",
 "Open FSD agent in browser": "FSD ajanını tarayıcıda aç",
 "Open Pull Request tab": "Pull Request Sekmesini Aç",
 "Open Workspace": "Çalışma Alanını Aç", "Open external link?": "Dış bağlantı açılsın mı?",
 "Open in Statsig": "Statsig'de Aç", "Open in internal browser": "Dahili tarayıcıda aç",
 "Open new tab menu": "Yeni sekme menüsünü aç", "Open pull request": "Pull request'i aç",
 "Paste as": "Farklı yapıştır",
 "Pending Opens": "Bekleyen Açılışlar", "Pending Range": "Bekleyen Aralık",
 "Pending Writes:": "Bekleyen Yazmalar:",
 "Performance & safety focused": "Performans ve güvenlik odaklı",
 "Plugin Tray Primary Action": "Eklenti Tepsisi Birincil Eylemi",
 "Post to Slack": "Slack'e Gönder",
 "Primary Action": "Birincil Eylem", "Process requires your attention": "İşlem ilginizi gerektiriyor",
 "Processing Primary": "Birincil İşleniyor",
 "Prompt w/ Never Show": "Bir Daha Gösterme ile İstem",
 "Queued messages": "Sıradaki mesajlar",
 "Rate Limited (Changeable)": "Hız Sınırlı (Değiştirilebilir)",
 "Reduce Motion": "Hareketi Azalt",
 "Refreshing Changes": "Değişiklikler Yenileniyor",
 "Remember for this workspace": "Bu çalışma alanı için hatırla",
 "Removed from ": "Şuradan kaldırıldı: ",
 "Replace all": "Tümünü değiştir", "Reply to review thread": "İnceleme dizisine yanıt ver",
 "Repositories and branches": "Depolar ve dallar",
 "Requested reviewers": "İstenen incelemeciler",
 "Reset In-App Ad Views": "Uygulama İçi Reklam Görüntülemelerini Sıfırla",
 "Resolve Workspace Path For Inline Code": "Satır İçi Kod İçin Çalışma Alanı Yolunu Çöz",
 "Resource Exhausted": "Kaynak Tükendi",
 "Retained by": "Şunun tarafından tutuluyor:",
 "Review required": "İnceleme gerekli",
 "Run history": "Çalıştırma geçmişi", "Run ownership": "Çalıştırma sahipliği",
 "Sample diff preview for the code font": "Kod yazı tipi için örnek fark önizlemesi",
 "Search favorites and history": "Favorilerde ve geçmişte ara",
 "Search or enter URL": "Arayın veya URL girin",
 "Second choice": "İkinci seçenek",
 "Select a project": "Bir proje seçin",
 "Selection actions": "Seçim eylemleri",
 "Self-Driving Mode": "Otomatik Sürüş Modu", "Self-hosted pools": "Kendinden barındırmalı havuzlar",
 "Send Test Notification": "Test Bildirimi Gönder", "Send now": "Şimdi gönder", "Send to Cloud": "Buluta Gönder",
 "Set Value": "Değer Ayarla",
 "Shared Library": "Paylaşılan Kitaplık",
 "Show Chat": "Sohbeti Göster", "Show PR filters": "PR filtrelerini göster",
 "Show Sidebar": "Kenar Çubuğunu Göster",
 "Show environment filters": "Ortam filtrelerini göster", "Show files": "Dosyaları göster",
 "Show panel actions": "Panel eylemlerini göster", "Show source filters": "Kaynak filtrelerini göster",
 "Show status filters": "Durum filtrelerini göster", "Show tour": "Turu göster",
 "Start File Watch Recording": "Dosya İzleme Kaydını Başlat",
 "Start When I Open a PR": "PR Açtığımda Başlat",
 "Stop file watch recording": "Dosya izleme kaydını durdur", "Stop forwarding": "İletmeyi durdur",
 "Suggestion list": "Öneri listesi",
 "Switch to Model Slug": "Model Kısa Adına Geç", "Switch to Model Slug In Glass": "Glass'ta Model Kısa Adına Geç",
 "Table view": "Tablo görünümü",
 "Target environment: cloud": "Hedef ortam: bulut", "Target environment: local": "Hedef ortam: yerel",
 "Team agents shown in sidebar": "Kenar çubuğunda gösterilen ekip ajanları",
 "Text Only": "Yalnızca Metin",
 "This action is initially disabled": "Bu eylem başlangıçta devre dışı",
 "This action is now enabled": "Bu eylem artık etkin",
 "This is a high priority notification": "Bu yüksek öncelikli bir bildirim",
 "This is a warning notification": "Bu bir uyarı bildirimi",
 "This is an error notification": "Bu bir hata bildirimi",
 "This is an info notification": "Bu bir bilgi bildirimi",
 "This menu has": "Bu menüde var:",
 "This notification includes a source": "Bu bildirim bir kaynak içerir",
 "Toggle Composer Location": "Composer Konumunu Aç/Kapat",
 "Tracked repositories": "İzlenen depolar",
 "Try resizing this": "Bunu yeniden boyutlandırmayı deneyin",
 "TypeScript-based framework": "TypeScript tabanlı çerçeve",
 "Typed superset of JavaScript": "JavaScript'in türetilmiş üst kümesi",
 "Unknown model (fallback formatting)": "Bilinmeyen model (yedek biçimlendirme)",
 "Updating pull request": "Pull request güncelleniyor",
 "Usage Pricing (Changeable)": "Kullanım Fiyatlandırması (Değiştirilebilir)",
 "Use Existing": "Mevcut Olanı Kullan", "Use Regular Expression": "Normal İfade Kullan",
 "Use regular expression": "normal ifade kullan",
 "WSL Connect Dialog Back": "WSL Bağlan İletişim Kutusu Geri",
 "What do these metrics mean?": "Bu ölçümler ne anlama geliyor?",
 "With Diff Stats (Large)": "Fark İstatistikleriyle (Büyük)",
 "With Diff Stats (Medium)": "Fark İstatistikleriyle (Orta)",
 "With Diff Stats (Small)": "Fark İstatistikleriyle (Küçük)",
 "With Icon": "Simgeli", "With Links": "Bağlantılı", "With Plan": "Planlı",
 "With Source": "Kaynaklı", "With Tooltip": "İpuçlu", "With Unread Indicator": "Okunmamış Göstergeli",
}

if __name__ == '__main__':
    for fname in ['workbench.desktop.main.js', 'workbench.glass.main.js']:
        s = io.open(fname, encoding='utf-8').read()
        n = 0
        for en, tr in TR.items():
            a = '"%s"' % en
            b = '"%s"' % tr
            c = s.count(a)
            if c:
                s = s.replace(a, b)
                n += c
        io.open(fname, 'w', encoding='utf-8', newline='').write(s)
        print(fname, 'degisim:', n)
