# -*- coding: utf-8 -*-
# Komut paleti / ipucu basliklari: value:"EN",original:"EN" kalibinda yalnizca
# value kismi cevrilir (original, Ingilizce aramanin calismasi icin kalir).
import io

TR = {
 "AI Tracking": "Yapay Zeka İzleme",
 "Accept & Run Generated Command": "Üretilen Komutu Kabul Et ve Çalıştır",
 "Accept Generated Command": "Üretilen Komutu Kabul Et",
 "Accept pending agent pane action": "Bekleyen ajan paneli eylemini kabul et",
 "Add Files to Chat": "Dosyaları Sohbete Ekle",
 "Add Files to New Chat": "Dosyaları Yeni Sohbete Ekle",
 "Add New Custom Docs": "Yeni Özel Belge Ekle",
 "Add model to switcher": "Modeli değiştiriciye ekle",
 "Agent Settings": "Ajan Ayarları",
 "Approve pending shell tool (run)": "Bekleyen kabuk aracını onayla (çalıştır)",
 "Approve pending shell tool and allowlist": "Bekleyen kabuk aracını onayla ve izin listesine ekle",
 "Attempt Update": "Güncellemeyi Dene",
 "Cancel Chat": "Sohbeti İptal Et",
 "Cancel Chat (Input Focused)": "Sohbeti İptal Et (Giriş Odaklı)",
 "Cancel Generation": "Üretimi İptal Et",
 "Cancel Terminal Tool Call": "Terminal Araç Çağrısını İptal Et",
 "Cancel Voice Mode": "Sesli Modu İptal Et",
 "Check for Update": "Güncellemeyi Denetle",
 "Clear All MCP Tokens": "Tüm MCP Belirteçlerini Temizle",
 "Close Agent Changes": "Ajan Değişikliklerini Kapat",
 "Close Agents window": "Ajanlar penceresini kapat",
 "Close Find in Chat": "Sohbette Bulmayı Kapat",
 "Close Prompt Bar": "İstem Çubuğunu Kapat",
 "Configure Local Agent": "Yerel Ajanı Yapılandır",
 "Convert Legacy Agent Applied Rules": "Eski Ajan Uygulanan Kurallarını Dönüştür",
 "Copy Request ID": "İstek Kimliğini Kopyala",
 "Create New Composer": "Yeni Composer Oluştur",
 "Create Rule": "Kural Oluştur",
 "Create Worktree / Submit": "Çalışma Ağacı Oluştur / Gönder",
 "Cursor Vim: Remove Vim Mode": "Cursor Vim: Vim Modunu Kaldır",
 "Cycle model parameter": "Model parametresini döngüle",
 "Delete Old Chats...": "Eski Sohbetleri Sil...",
 "Disable Autocompletes": "Otomatik Tamamlamaları Devre Dışı Bırak",
 "Disable Fallback Models": "Yedek Modelleri Devre Dışı Bırak",
 "Export Transcript": "Konuşma Dökümünü Dışa Aktar",
 "Find All Implementations": "Tüm Uygulamaları Bul",
 "Find All References": "Tüm Referansları Bul",
 "Find Next in Chat": "Sohbette Sonrakini Bul",
 "Find Previous in Chat": "Sohbette Öncekini Bul",
 "Find in Chat": "Sohbette Bul",
 "Focus AI Settings Search": "Yapay Zeka Ayar Aramasına Odaklan",
 "Focus Agent": "Ajana Odaklan",
 "Focus Chat Followup": "Sohbet Devam Alanına Odaklan",
 "Focus Edit": "Düzenlemeye Odaklan",
 "Fork Chat": "Sohbeti Çatalla",
 "Fork Shared Chat": "Paylaşılan Sohbeti Çatalla",
 "Generate Commit Message": "Commit Mesajı Üret",
 "Generate an Image": "Görsel Üret",
 "Generate in Terminal": "Terminalde Üret",
 "Give Feedback": "Geri Bildirim Ver",
 "Go to Definition From Chat Response": "Sohbet Yanıtından Tanıma Git",
 "Hide Chat": "Sohbeti Gizle",
 "Hide Prompt Bar": "İstem Çubuğunu Gizle",
 "Index Main Repository": "Ana Depoyu Dizinle",
 "Initialize user level hooks": "Kullanıcı düzeyi kancaları başlat",
 "Insert Edit Selection": "Düzenleme Seçimini Ekle",
 "Maximize Agents window": "Ajanlar penceresini büyüt",
 "Minimize Agents window": "Ajanlar penceresini küçült",
 "More Actions": "Diğer Eylemler",
 "New Chat": "Yeni Sohbet",
 "New Chat Tab": "Yeni Sohbet Sekmesi",
 "New Chat with Selections": "Seçimlerle Yeni Sohbet",
 "Next Prompt Bar": "Sonraki İstem Çubuğu",
 "Next chat tab": "Sonraki sohbet sekmesi",
 "Open Account Settings": "Hesap Ayarlarını Aç",
 "Open Agent Changes": "Ajan Değişikliklerini Aç",
 "Open Agent as Pane": "Ajanı Bölme Olarak Aç",
 "Open Branch Menu": "Dal Menüsünü Aç",
 "Open Browser": "Tarayıcıyı Aç",
 "Open Chat": "Sohbeti Aç",
 "Open Composer": "Composer'ı Aç",
 "Open File": "Dosya Aç",
 "Open File Diff": "Dosya Farkını Aç",
 "Open Local Agent Logs": "Yerel Ajan Günlüklerini Aç",
 "Open New Agent Chat": "Yeni Ajan Sohbeti Aç",
 "Open Terminal in Worktree": "Çalışma Ağacında Terminal Aç",
 "Open Virtual Machine": "Sanal Makineyi Aç",
 "Open Window for Background Composer": "Arka Plan Composer'ı için Pencere Aç",
 "Open add context menu": "Bağlam ekleme menüsünü aç",
 "Open chat mode menu": "Sohbet modu menüsünü aç",
 "Open in Prompt Quality": "Prompt Quality'de Aç",
 "Open in Web": "Web'de Aç",
 "Open model toggle": "Model değiştiriciyi aç",
 "Previous chat tab": "Önceki sohbet sekmesi",
 "Reject Generated Command": "Üretilen Komutu Reddet",
 "Remove Followup": "Devam Önerisini Kaldır",
 "Rename Chat": "Sohbeti Yeniden Adlandır",
 "Reset Mode to Default": "Modu Varsayılana Sıfırla",
 "Resolve All Conflicts in Chat": "Sohbetteki Tüm Çakışmaları Çöz",
 "Resolve Conflict in Cmd+K": "Cmd+K'de Çakışmayı Çöz",
 "Restore Agents window": "Ajanlar penceresini geri yükle",
 "Resume Current Chat": "Geçerli Sohbete Devam Et",
 "Reveal AI Code Tracking Paths": "Yapay Zeka Kod İzleme Yollarını Göster",
 "Revert File": "Dosyayı Geri Al",
 "Rename Chat Tab": "Sohbet Sekmesini Yeniden Adlandır",
 "Select Last SubComposer Tab": "Son SubComposer Sekmesini Seç",
 "Select Next Chat": "Sonraki Sohbeti Seç",
 "Select Next SubComposer Tab": "Sonraki SubComposer Sekmesini Seç",
 "Select Previous Chat": "Önceki Sohbeti Seç",
 "Select Previous SubComposer Tab": "Önceki SubComposer Sekmesini Seç",
 "Select SubComposer Tab 1": "SubComposer Sekmesi 1'i Seç",
 "Select SubComposer Tab 2": "SubComposer Sekmesi 2'yi Seç",
 "Select SubComposer Tab 3": "SubComposer Sekmesi 3'ü Seç",
 "Select SubComposer Tab 4": "SubComposer Sekmesi 4'ü Seç",
 "Select SubComposer Tab 5": "SubComposer Sekmesi 5'i Seç",
 "Select SubComposer Tab 6": "SubComposer Sekmesi 6'yı Seç",
 "Select SubComposer Tab 7": "SubComposer Sekmesi 7'yi Seç",
 "Select SubComposer Tab 8": "SubComposer Sekmesi 8'i Seç",
 "Share Canvas": "Canvas'ı Paylaş",
 "Share Feedback": "Geri Bildirim Paylaş",
 "Share Transcript": "Konuşma Dökümünü Paylaş",
 "Sign Out of GitHub": "GitHub Oturumunu Kapat",
 "Skip pending shell tool": "Bekleyen kabuk aracını atla",
 "Submit Fix": "Düzeltmeyi Gönder",
 "Swap Agent Sidebar Location": "Ajan Kenar Çubuğu Konumunu Değiştir",
 "Switch to model": "Modele geç",
 "Toggle Voice Mode": "Sesli Modu Aç/Kapat",
 "Toggle open as editor": "Düzenleyici olarak açmayı aç/kapat",
 "Turn Cmd+K to Composer": "Cmd+K'yi Composer'a Dönüştür",
}

if __name__ == '__main__':
    for fname in ['workbench.desktop.main.js', 'workbench.glass.main.js']:
        s = io.open(fname, encoding='utf-8').read()
        n = 0
        for en, tr in TR.items():
            a = 'value:"%s",original:"' % en
            b = 'value:"%s",original:"' % tr
            c = s.count(a)
            if c:
                s = s.replace(a, b)
                n += c
        io.open(fname, 'w', encoding='utf-8', newline='').write(s)
        print(fname, 'degisim:', n)
