# -*- coding: utf-8 -*-
"""Taramada bilinen listesine saklanmis, gercek kullanici arayuzu metinleri."""
import io, re

FILES = [
    'nls.messages.json', 'nls.cache.messages.json',
    'workbench.desktop.main.js', 'workbench.glass.main.js',
    'cursor-agent-exec-main.js', 'cursor-local-agent-runtime-main.js',
]

# Yalnizca gorunur UI ozelliklerinde degistirilir; protokol anahtarlari ve
# program mantiginda kullanilan serbest string sabitleri etkilenmez.
MAP = {
    '(from file)': '(dosyadan)',
    '(from JSON)': '(JSON dosyasından)',
    'A secret with this name already exists in this scope.': 'Bu kapsamda aynı ada sahip bir gizli değer zaten var.',
    'Accepted formats: PNG, JPEG, or WebP up to 2 MB': 'Kabul edilen biçimler: En fazla 2 MB PNG, JPEG veya WebP',
    'Chat title. Right-click for more actions.': 'Sohbet başlığı. Diğer işlemler için sağ tıklayın.',
    'Check run annotations': 'Kontrol çalıştırma ek açıklamaları',
    'Commented': 'Yorum yapıldı',
    'Completed': 'Tamamlandı',
    'Detailed, edits with diffs and shells with output': 'Ayrıntılı; farklarla düzenlemeler ve çıktılı kabuklar',
    'Done': 'Bitti',
    'Error': 'Hata',
    'Failed': 'Başarısız',
    'Installing': 'Yükleniyor',
    'Installing extensions...': 'Eklentiler yükleniyor...',
    'Loading Checks': 'Kontroller yükleniyor',
    'Loading cloud agent changes': 'Bulut ajanı değişiklikleri yükleniyor',
    'Loading cloud MCP servers...': 'Bulut MCP sunucuları yükleniyor...',
    'Loading file': 'Dosya yükleniyor',
    'Loading home MCP servers...': 'Ana MCP sunucuları yükleniyor...',
    'Loading installed MCP servers...': 'Yüklü MCP sunucuları yükleniyor...',
    'Loading MCP servers...': 'MCP sunucuları yükleniyor...',
    'Loading Mermaid preview': 'Mermaid önizlemesi yükleniyor',
    'Loading side chat': 'Yan sohbet yükleniyor',
    'Loading terminal': 'Terminal yükleniyor',
    'Loading user MCP servers...': 'Kullanıcı MCP sunucuları yükleniyor...',
    'Loading workspace MCP servers...': 'Çalışma alanı MCP sunucuları yükleniyor...',
    'Loading your profile': 'Profiliniz yükleniyor',
    'Maximum token limit exceeded.': 'En yüksek token sınırı aşıldı.',
    'Model blocked.': 'Model engellendi.',
    'Named Agent unavailable': 'Adlandırılmış Ajan kullanılamıyor',
    'Next': 'İleri',
    'No changes detected in the worktree.': 'Çalışma ağacında değişiklik algılanmadı.',
    'No checkout conflicts detected. Switching branch...': 'Dal değiştirme çakışması bulunmadı. Dal değiştiriliyor...',
    'No recent commits found in selected repositories.': 'Seçili depolarda yakın tarihli commit bulunamadı.',
    'No repositories found.': 'Depo bulunamadı.',
    'No workspace folders are open.': 'Açık çalışma alanı klasörü yok.',
    'Only HTTPS authentication URLs are supported for cloud MCP servers.': 'Bulut MCP sunucuları için yalnızca HTTPS kimlik doğrulama adresleri desteklenir.',
    'OpenAI rate limit exceeded.': 'OpenAI hız sınırı aşıldı.',
    'OpenAI service error.': 'OpenAI hizmet hatası.',
    'Opening destination workspace...': 'Hedef çalışma alanı açılıyor...',
    'Operation in progress...': 'İşlem sürüyor...',
    'Pending': 'Bekliyor',
    'Pinned': 'Sabitlendi',
    'Please configure your environment for cloud agents.': 'Lütfen bulut ajanları için ortamınızı yapılandırın.',
    'Please wait while the operation is being processed...': 'İşlem yürütülürken lütfen bekleyin...',
    'Preparing cloud migration data...': 'Bulut taşıma verileri hazırlanıyor...',
    'Preparing migrated conversation...': 'Taşınan konuşma hazırlanıyor...',
    'Preparing worktree for migration...': 'Çalışma ağacı taşıma için hazırlanıyor...',
    'Pro user only feature.': 'Yalnızca Pro kullanıcılara açık özellik.',
    'Pro user rate limit exceeded.': 'Pro kullanıcı hız sınırı aşıldı.',
    'Pro user usage limit reached.': 'Pro kullanıcı kullanım sınırına ulaşıldı.',
    'Pushing to remote...': 'Uzak depoya gönderiliyor...',
    'Rate limit exceeded.': 'Hız sınırı aşıldı.',
    'Recording interrupted. Please try again.': 'Kayıt kesintiye uğradı. Lütfen yeniden deneyin.',
    'Repository not initialized.': 'Depo başlatılmamış.',
    'Resolving shell environment...': 'Kabuk ortamı çözümleniyor...',
    'Resource not found.': 'Kaynak bulunamadı.',
    'Restoring conversation history...': 'Konuşma geçmişi geri yükleniyor...',
    'Run Everything is already enabled for this agent': 'Her Şeyi Çalıştır bu ajan için zaten etkin',
    'Running': 'Çalışıyor',
    'Saving migrated agent...': 'Taşınan ajan kaydediliyor...',
    'Scroll to bottom': 'En alta kaydır',
    'Side chats cannot be moved to another location': 'Yan sohbetler başka bir konuma taşınamaz',
    'Skipped': 'Atlandı',
    'Starting multi-stage process...': 'Çok aşamalı işlem başlatılıyor...',
    'Success': 'Başarılı',
    'The operation was completed successfully!': 'İşlem başarıyla tamamlandı!',
    'Triggered reconnect for the active agent workspace.': 'Etkin ajan çalışma alanı için yeniden bağlantı başlatıldı.',
    'Warning': 'Uyarı',
    "Your handle can't be changed once claimed": 'Kullanıcı adınız alındıktan sonra değiştirilemez',
    'Prevent "Connection failed" errors when paused at breakpoints during debugging. This works by disabling HTTP/2 keepalive pings.': 'Hata ayıklama sırasında kesme noktalarında duraklatıldığında "Bağlantı başarısız" hatalarını önleyin. Bu, HTTP/2 canlı tutma sinyallerini devre dışı bırakır.',
    'When enabled, your email address will be partially masked in the settings UI to protect your privacy (e.g., "j***@example.com").': 'Etkinleştirildiğinde gizliliğinizi korumak için e-posta adresiniz ayarlar arayüzünde kısmen maskelenir (ör. "j***@example.com").',
}

# Bazı görünür düğme metinleri bir prop içinde değil, minify edilmiş yardımcı
# fonksiyon çağrısının ilk argümanı olarak tutuluyor. Bu benzersiz UI sabitleri
# için tırnaklı birebir değişim güvenlidir ve minify edilmiş fonksiyon adı
# sürümler arasında değişse bile çalışır.
DIRECT_MAP = {
    'New Chat': 'Yeni Sohbet',
    # Cursor 3.14.27 yeni proje, eklenti pazari ve izleme yuzeyleri
    'Allow Members to Publish': 'Üyelerin Yayınlamasına İzin Ver',
    'Attached Live': 'Canlı Bağlandı',
    'Chat switch traces are sampled at 100% while this panel is open': 'Bu panel açıkken sohbet geçişi izleri %100 oranında örneklenir',
    'Group PRs by status': 'Pull Requestleri Duruma Göre Grupla',
    'Group pull requests into Open, Draft, Merged, and Closed sections in the supplemental sidebar': 'Pull requestleri ek kenar çubuğunda Açık, Taslak, Birleştirilmiş ve Kapatılmış bölümlerinde grupla',
    'Hydration': 'İçerik Hazırlama',
    'Let any team member publish plugins to this marketplace. When off, only team admins can publish.': 'Her ekip üyesinin bu pazarda eklenti yayınlamasına izin ver. Kapalıyken yalnızca ekip yöneticileri yayınlayabilir.',
    'Loading notes...': 'Notlar yükleniyor...',
    'No notes yet': 'Henüz not yok',
    'Open in Design Mode': 'Tasarım Modunda Aç',
    'Open project agents page': 'Proje ajanları sayfasını aç',
    'Open project pull requests page': 'Proje pull requestleri sayfasını aç',
    'Plugins, MCPs, Skills, and Rules have moved to Customize': 'Eklentiler, MCP’ler, Beceriler ve Kurallar Özelleştir bölümüne taşındı',
    'Project notes unavailable': 'Proje notları kullanılamıyor',
    'Shell presented': 'Kabuk gösterildi',
    'Show Projects as Agents across the app. When off, the UI reads Projects.': 'Projeleri uygulama genelinde Ajanlar olarak göster. Kapalıyken arayüzde Projeler yazar.',
    'Show Tasks, Agents, and pull request pills on Projects': 'Projelerde Görev, Ajan ve pull request etiketlerini göster',
    'Sign-in restricted': 'Oturum açma kısıtlandı',
    'Skill publishing': 'Beceri yayınlama',
    'Trace started': 'İzleme başlatıldı',
    'Transcript settled': 'Döküm tamamlandı',
    'User Input Required': 'Kullanıcı Girdisi Gerekli',
    'Visible content ready': 'Görünür içerik hazır',
    'Waiting for a chat switch': 'Sohbet geçişi bekleniyor',
    "We've introduced a new home for all the ways to customize Cursor.": 'Cursor’ı özelleştirmenin tüm yolları için yeni bir merkez oluşturduk.',
    # Cursor 3.14.7 yeni ajan/proje/eklenti yuzeyleri
    'Add Agents & Project Context': 'Ajan ve Proje Bağlamı Ekle',
    'Add install commands for this environment': 'Bu ortam için kurulum komutları ekle',
    'Agent unavailable': 'Ajan kullanılamıyor',
    'Agent-managed pull requests': 'Ajan tarafından yönetilen pull requestler',
    'Anyone with the link': 'Bağlantıya sahip herkes',
    'Artifact sharing': 'Artefakt paylaşımı',
    'Automatically resume the Project coordinator when a thread completes': 'Bir görev tamamlandığında Proje koordinatörünü otomatik sürdür',
    'Changed files': 'Değişen dosyalar',
    'Clone a Git repository and add it as a project.': 'Bir Git deposunu klonlayıp proje olarak ekleyin.',
    'Close tray': 'Tepsiyi kapat',
    'Cloud agent environment setup': 'Bulut ajanı ortam kurulumu',
    'Continue interrupted agents on relaunch': 'Yeniden açılışta kesilen ajanları sürdür',
    "Couldn't connect to the cloud environment": 'Bulut ortamına bağlanılamadı',
    "Couldn't load this conversation. Send a follow-up or reload the window to try again.": 'Bu konuşma yüklenemedi. Yeniden denemek için takip mesajı gönderin veya pencereyi yeniden yükleyin.',
    'Drag in chats, files, or links to get started.': 'Başlamak için sohbetleri, dosyaları veya bağlantıları sürükleyin.',
    'Editing goal...': 'Hedef düzenleniyor...',
    'Editing queued message...': 'Sıradaki mesaj düzenleniyor...',
    'Enter an https or SSH clone URL.': 'Bir HTTPS veya SSH klonlama URL’si girin.',
    'Environment details': 'Ortam ayrıntıları',
    'Error: open_scheduled_task is not enabled': 'Hata: open_scheduled_task etkin değil',
    'Failed to update the goal.': 'Hedef güncellenemedi.',
    'Fetches the latest origin/main and reports whether the current branch is behind.': 'En son origin/main dalını alır ve mevcut dalın geride olup olmadığını bildirir.',
    'Focus Next Tile': 'Sonraki Döşemeye Odaklan',
    'Have the project coordinator send all user-visible correspondence through a dedicated tool': 'Proje koordinatörünün kullanıcıya görünen tüm yazışmaları özel bir araç üzerinden göndermesini sağla',
    'Loading conversation': 'Konuşma yükleniyor',
    'Loading tasks...': 'Görevler yükleniyor...',
    'More message actions': 'Diğer mesaj işlemleri',
    'New chat': 'Yeni sohbet',
    'No matching plans': 'Eşleşen plan yok',
    'No pull requests yet.': 'Henüz pull request yok.',
    'No recent agents yet.': 'Henüz son ajan yok.',
    'No sign-in required': 'Oturum açma gerekmez',
    'No tasks brief yet.': 'Henüz görev özeti yok.',
    'Open Desktop': 'Masaüstünü Aç',
    'Open Link': 'Bağlantıyı Aç',
    'Open editor panel': 'Düzenleyici panelini aç',
    'Open in External Browser': 'Harici Tarayıcıda Aç',
    'Open marketplace repository': 'Marketplace deposunu aç',
    'Open project tasks page': 'Proje görevleri sayfasını aç',
    'PRs database not found in overview.md': 'overview.md içinde PR veritabanı bulunamadı',
    'Playback speed': 'Oynatma hızı',
    'Project card selection actions': 'Proje kartı seçim işlemleri',
    'Project tasks and managed pull requests': 'Proje görevleri ve yönetilen pull requestler',
    'Repository URL (https or SSH)': 'Depo URL’si (HTTPS veya SSH)',
    'Reset this pane to a new agent': 'Bu paneli yeni bir ajana sıfırla',
    'Reset this pane to a new agent. In a tileset, replaces the current tile with a blank draft instead of leaving the tileset.': 'Bu paneli yeni bir ajana sıfırlar. Döşeme kümesinde mevcut döşemeyi boş taslakla değiştirir.',
    'Scheduled task run target': 'Zamanlanmış görev çalıştırma hedefi',
    'Sends without interrupting the agent': 'Ajanı kesmeden gönderir',
    'Show Remote SSH Output': 'Remote SSH Çıktısını Göster',
    'Show an expandable Project pill for Tasks, Working, and pull requests': 'Görevler, Çalışanlar ve pull requestler için genişletilebilir Proje rozeti göster',
    'Skill link copied to clipboard.': 'Beceri bağlantısı panoya kopyalandı.',
    'Staged project items': 'Hazırlanan proje öğeleri',
    'Sync chats and continue them in Cursor': 'Sohbetleri eşitleyin ve Cursor’da devam edin',
    'The Remote - SSH workspace is not available yet.': 'Remote - SSH çalışma alanı henüz kullanılamıyor.',
    'Treated the singleton property object as a one-entry properties list': 'Tekil özellik nesnesi tek girdili özellik listesi olarak işlendi',
    'Treated the singleton task object as a one-entry tasks list': 'Tekil görev nesnesi tek girdili görev listesi olarak işlendi',
    'Unable to load this step.': 'Bu adım yüklenemedi.',
    'Unworked branch warning': 'Çalışılmamış dal uyarısı',
    'Use Send Message tool': 'Mesaj Gönder aracını kullan',
    'Use in IDE': 'IDE’de Kullan',
    'Wake Project when threads finish': 'Görevler bitince Projeyi uyandır',
    'When Cursor closes while an agent is working, pick the agent back up the next time you open Cursor.': 'Cursor, ajan çalışırken kapanırsa Cursor’u yeniden açtığınızda ajanı kaldığı yerden sürdür.',
    'with warnings': 'uyarılarla',
    'Configure an extension to execute in a different extension host process.': 'Bir eklentiyi farklı bir eklenti ana makine sürecinde çalışacak şekilde yapılandırın.',
    'Configure the Marketplace service URL to connect to': 'Bağlanılacak Marketplace hizmet URL’sini yapılandırın',
    'Controls the automatic update behavior of extensions. The updates are fetched from a Microsoft online service.': 'Eklentilerin otomatik güncelleme davranışını denetler. Güncellemeler Microsoft çevrimiçi hizmetinden alınır.',
    'Controls the delay in milliseconds before hovers in the Cursor Blame panes appear. If not set, uses `#editor.hover.delay#` with a minimum of 500ms.': 'Cursor Blame panellerinde fare üstü ipuçlarının görünmeden önceki gecikmesini milisaniye cinsinden denetler. Ayarlanmazsa en az 500 ms olacak şekilde `#editor.hover.delay#` kullanılır.',
    'Controls the timeout in milliseconds for HTTP requests made when fetching extensions from the Marketplace.': 'Marketplace’ten eklenti alınırken yapılan HTTP isteklerinin zaman aşımını milisaniye cinsinden denetler.',
    'Cursor will pick these agents back up when you reopen.': 'Yeniden açtığınızda Cursor bu ajanları kaldığı yerden sürdürecek.',
    'Cursor will pick this agent back up when you reopen.': 'Yeniden açtığınızda Cursor bu ajanı kaldığı yerden sürdürecek.',
    'Defines the untrusted workspace support setting for the extension.': 'Eklenti için güvenilmeyen çalışma alanı destek ayarını tanımlar.',
    'Defines the version of the extension for which the override should be applied. If not specified, the override will be applied independent of the extension version.': 'Geçersiz kılmanın uygulanacağı eklenti sürümünü tanımlar. Belirtilmezse geçersiz kılma eklenti sürümünden bağımsız uygulanır.',
    'Enable web worker extension host.': 'Web worker eklenti ana makinesini etkinleştir.',
    "Extension '{0}' is a Built-in extension and cannot be installed": "Eklenti '{0}' yerleşik eklentidir ve kurulamaz",
    "Extension '{0}' is not installed. Make sure you use the full extension ID, including the publisher, e.g.: anysphere.csharp.": "Eklenti '{0}' kurulu değil. Yayıncıyı da içeren tam eklenti kimliğini kullandığınızdan emin olun, örn.: anysphere.csharp.",
    "Extension '{0}' not found.": "Eklenti '{0}' bulunamadı.",
    'Extension id or VSIX resource uri': 'Eklenti kimliği veya VSIX kaynak URI’si',
    'Extension id required.': 'Eklenti kimliği gerekli.',
    'Extension will always be enabled, and the extension will hide functionality requiring trust.': 'Eklenti her zaman etkin olur ve güven gerektiren işlevleri gizler.',
    'Extension will always be enabled.': 'Eklenti her zaman etkin olur.',
    'Extension will only be enabled only when the workspace is trusted.': 'Eklenti yalnızca çalışma alanı güvenilir olduğunda etkin olur.',
    'Id of the extension to uninstall': 'Kaldırılacak eklentinin kimliği',
    'If activated, extensions will automatically restart following an update if the window is not in focus. There can be a data loss if you have open Notebooks or Custom Editors.': 'Etkinleştirilirse pencere odakta değilken güncelleme sonrası eklentiler otomatik yeniden başlatılır. Açık Notebook veya Özel Düzenleyiciler varsa veri kaybı olabilir.',
    'Install the given extension': 'Belirtilen eklentiyi kur',
    "Justification for installing the extension. This is a string or an object that can be used to pass any information to the installation handlers. i.e. `{reason: 'This extension wants to open a URI', action: 'Open URI'}` will show a message box with the reason and action upon install.": "Eklenti kurulum gerekçesi. Kurulum işleyicilerine bilgi aktarmak için kullanılabilecek bir metin veya nesnedir. Örn. `{reason: 'Bu eklenti bir URI açmak istiyor', action: 'URI Aç'}` kurulum sırasında gerekçe ve eylemi içeren bir mesaj kutusu gösterir.",
    'Override the untrusted workspace support of an extension. Extensions using `true` will always be enabled. Extensions using `limited` will always be enabled, and the extension will hide functionality that requires trust. Extensions using `false` will only be enabled only when the workspace is trusted.': 'Bir eklentinin güvenilmeyen çalışma alanı desteğini geçersiz kılın. `true` kullanan eklentiler her zaman etkin olur. `limited` kullananlar her zaman etkin olur ve güven gerektiren işlevleri gizler. `false` kullananlar yalnızca çalışma alanı güvenilir olduğunda etkin olur.',
    'Override the virtual workspaces support of an extension.': 'Bir eklentinin sanal çalışma alanı desteğini geçersiz kılın.',
    'Query to use in search': 'Aramada kullanılacak sorgu',
    'Reload Now': 'Şimdi Yeniden Yükle',
    'Resume agent automatically': 'Ajanı otomatik sürdür',
    'Resume agents automatically': 'Ajanları otomatik sürdür',
    'Search for a specific extension': 'Belirli bir eklentiyi ara',
    'Show Running Extensions': 'Çalışan Eklentileri Göster',
    'The Web Worker Extension Host will always be launched.': 'Web Worker Eklenti Ana Makinesi her zaman başlatılır.',
    'The Web Worker Extension Host will be launched when a web extension needs it.': 'Bir web eklentisi ihtiyaç duyduğunda Web Worker Eklenti Ana Makinesi başlatılır.',
    'The Web Worker Extension Host will never be launched.': 'Web Worker Eklenti Ana Makinesi hiçbir zaman başlatılmaz.',
    'The following extensions were found to be problematic and have been uninstalled: {0}': 'Şu eklentiler sorunlu bulundu ve kaldırıldı: {0}',
    "This setting is deprecated. Use extensions.ignoreRecommendations setting to control recommendation notifications. Use Extensions view's visibility actions to hide Recommended view by default.": 'Bu ayar kullanımdan kaldırıldı. Öneri bildirimlerini denetlemek için extensions.ignoreRecommendations ayarını kullanın. Önerilen görünümünü varsayılan olarak gizlemek için Eklentiler görünümünün görünürlük eylemlerini kullanın.',
    'Uninstall the given extension': 'Belirtilen eklentiyi kaldır',
    'When an extension is listed here, a confirmation prompt will not be shown when that extension handles a URI.': 'Bir eklenti burada listelendiğinde, o eklenti bir URI işlediğinde onay istemi gösterilmez.',
    'When enabled, VS Code do not sync this extension when Settings Sync is on.': 'Etkinleştirildiğinde, Ayar Eşitleme açıkken VS Code bu eklentiyi eşitlemez.',
    'When enabled, VS Code installs only newly added extensions from the extension pack VSIX. This option is considered only while installing a VSIX.': 'Etkinleştirildiğinde VS Code, eklenti paketi VSIX içinden yalnızca yeni eklenen eklentileri kurar. Bu seçenek yalnızca VSIX kurulurken dikkate alınır.',
    'When enabled, VS Code installs the pre-release version of the extension if available.': 'Etkinleştirildiğinde VS Code, varsa eklentinin ön sürümünü kurar.',
    'When enabled, automatically checks extensions for updates. If an extension has an update, it is marked as outdated in the Extensions view. The updates are fetched from a Microsoft online service.': 'Etkinleştirildiğinde eklenti güncellemelerini otomatik kontrol eder. Güncellemesi olan eklenti, Eklentiler görünümünde güncel değil olarak işaretlenir. Güncellemeler Microsoft çevrimiçi hizmetinden alınır.',
    'When enabled, editors with extension details will be automatically closed upon navigating away from the Extensions View.': 'Etkinleştirildiğinde, Eklentiler görünümünden ayrılınca eklenti ayrıntılarını gösteren düzenleyiciler otomatik kapatılır.',
    'When enabled, extensions which declare the `onStartupFinished` activation event will be activated after a timeout.': 'Etkinleştirildiğinde `onStartupFinished` etkinleştirme olayını bildiren eklentiler zaman aşımından sonra etkinleştirilir.',
    'When enabled, the extension will be enabled if it is installed but disabled. If the extension is already enabled, this has no effect.': 'Etkinleştirildiğinde, eklenti kurulu ama devre dışıysa etkinleştirilir. Eklenti zaten etkinse etkisi olmaz.',
    'When enabled, the notifications for extension recommendations will not be shown.': 'Etkinleştirildiğinde eklenti önerisi bildirimleri gösterilmez.',
    'Choose a Different Model': 'Farklı Bir Model Seç',
    'Continue Working': 'Çalışmaya Devam Et',
    'No Destinations Available': 'Kullanılabilir Hedef Yok',
    'Send follow-up': 'Takip Mesajı Gönder',
    'New Automation': 'Yeni Otomasyon',
    'Automate repetitive tasks with always-on cloud agents that respond to environment triggers.': 'Ortam tetikleyicilerine yanıt veren sürekli açık bulut ajanlarıyla tekrarlanan görevleri otomatikleştirin.',
    'No Automations Yet': 'Henüz Otomasyon Yok',
    'Switch Model': 'Model Değiştir',
    'Search or Paste Link': 'Ara veya Bağlantı Yapıştır',
    'Follow System High Contrast': 'Sistem Yüksek Karşıtlığını İzle',
    'Create project': 'Proje oluştur',
    'Create Project': 'Proje Oluştur',
    'Marketplace': 'Eklenti Pazarı',
    'PR markdown actions': 'PR markdown işlemleri',
    'Retarget File Tabs': 'Dosya Sekmelerini Yeniden Hedefle',
    'Search plans': 'Planlarda ara',
    'Toggle options': 'Seçenekleri aç/kapat',
    'Use /plan to improve agent execution with Plan Mode': '/plan ile Plan Modu’nu kullanarak ajan yürütmesini iyileştirin',
    'Use /create-hook to control and extend the agent loop with custom scripts': '/create-hook ile ajan döngüsünü özel betiklerle denetleyip genişletin',
    'Use /simplify to have Cursor review all changed files for code quality and efficiency': '/simplify ile Cursor’un tüm değişen dosyaları kod kalitesi ve verimlilik için incelemesini sağlayın',
    'Use /multitask so Cursor can work on your queued messages in parallel': '/multitask ile Cursor’un sıradaki mesajlarınız üzerinde paralel çalışmasını sağlayın',
    'Use': 'Kullan',
    'Use ': 'Kullan ',
    'Use /multitask to run subagents to parallelize your requests instead of queuing them': '/multitask ile isteklerinizi sıraya almak yerine paralel çalıştırmak için alt ajanları kullanın',
    'Try a new window for running parallel agents': 'Paralel ajanları çalıştırmak için yeni bir pencere deneyin',
    'After long sessions, use /split-to-prs to turn your work into small, reviewable PRs': 'Uzun oturumlardan sonra çalışmanızı küçük ve incelenebilir PR’lara bölmek için /split-to-prs kullanın',
    'Voice mode lets you dictate better prompts for your agents': 'Ses modu, ajanlarınız için daha iyi istemleri dikte etmenizi sağlar',
    'Use /ask to research your codebase before starting code changes': 'Kod değişikliklerine başlamadan önce kod tabanınızı araştırmak için /ask kullanın',
    'Ask Mode uses read-only agents to research your codebase – hit shift+tab to get started': 'Sor Modu, kod tabanınızı araştırmak için salt okunur ajanlar kullanır; başlamak için Shift+Tab tuşlarına basın',
    'Sor Mod uses read-only agents to research your codebase – hit shift+tab to get started': 'Sor Modu, kod tabanınızı araştırmak için salt okunur ajanlar kullanır; başlamak için Shift+Tab tuşlarına basın',
    'Cursor can respond with interactive visualizations alongside text – use /canvas to get started': 'Cursor, metnin yanında etkileşimli görselleştirmelerle yanıt verebilir; başlamak için /canvas kullanın',
    'Use /canvas to get interactive visualizations like dashboards from Cursor': '/canvas ile Cursor’dan pano gibi etkileşimli görselleştirmeler alın',
    'Use /automate to create Cursor Automations without leaving your agent chat': '/automate ile ajan sohbetinden ayrılmadan Cursor Otomasyonları oluşturun',
    'Use /cloud or /local to move agent sessions between runtimes': '/cloud veya /local ile ajan oturumlarını çalışma ortamları arasında taşıyın',
    'Use /cloud to run agents remotely for better parallelization and durable execution': '/cloud ile daha iyi paralelleştirme ve kalıcı yürütme için ajanları uzaktan çalıştırın',
    'Use /create-rule to control agent behavior through system-level instructions': '/create-rule ile ajan davranışını sistem düzeyi talimatlarla denetleyin',
    'Use /create-skill to customize Cursor for your workflows': '/create-skill ile Cursor’u iş akışlarınıza göre özelleştirin',
    'Use /create-subagent to set up specialized agents that Cursor can use to parallelize work': '/create-subagent ile Cursor’un işi paralelleştirmek için kullanabileceği uzman ajanlar kurun',
    'Use /debug to solve bugs that are hard to reproduce or understand': '/debug ile yeniden üretmesi veya anlaması zor hataları çözün',
    'Use /in-cloud to start a subagent in its own cloud VM, keeping your local workspace free': '/in-cloud ile yerel çalışma alanınızı boş tutarak alt ajanı kendi bulut VM’inde başlatın',
    'Kullan /in-cloud to start a subagent in its own cloud VM, keeping your local workspace free': '/in-cloud ile yerel çalışma alanınızı boş tutarak bir alt ajanı kendi bulut sanal makinesinde başlatın',
    'to start a subagent in its own cloud VM, keeping your local workspace free': 'ile yerel çalışma alanınızı boş tutarak bir alt ajanı kendi bulut sanal makinesinde başlatın',
    'Use /loop to run a prompt on a schedule': '/loop ile bir istemi zamanlamaya göre çalıştırın',
    'Use /model to pick the best model for your task and select Composer for a great balance of cost vs. capability': '/model ile göreviniz için en uygun modeli seçin; maliyet-yetenek dengesi için Composer’ı kullanın',
    'Use /shell to run commands in the terminal': '/shell ile terminalde komut çalıştırın',
    'Use /review for an agentic code review of your changes': '/review ile değişikliklerinizi ajan destekli kod incelemesinden geçirin',
    'Kullan /review for an agentic code review of your changes': '/review ile değişikliklerinizi ajan destekli kod incelemesinden geçirin',
    'Debug Mode reproduces and solves your most difficult bugs - hit shift+tab twice to get started': 'Hata Ayıklama Modu en zor hatalarınızı yeniden oluşturup çözer; başlamak için Shift+Tab tuşlarına iki kez basın',
    'Hata Ayıklama Modu reproduces and solves your most difficult bugs - hit shift+tab twice to get started': 'Hata Ayıklama Modu en zor hatalarınızı yeniden oluşturup çözer; başlamak için Shift+Tab tuşlarına iki kez basın',
    'Hata Ayıklama Mod reproduces and solves your most difficult bugs - hit shift+tab twice to get started': 'Hata Ayıklama Modu en zor hatalarınızı yeniden oluşturup çözer; başlamak için Shift+Tab tuşlarına iki kez basın',
    'reproduces and solves your most difficult bugs - hit shift+tab twice to get started': 'en zor hatalarınızı yeniden oluşturup çözer; başlamak için Shift+Tab tuşlarına iki kez basın',
    'Use /split-to-prs': '/split-to-prs ile çalışmanızı küçük PR’lara ayırın',
    'Use /automate': '/automate kullan',
    'Use /cloud': '/cloud kullan',
    'Use /cloud or /local': '/cloud veya /local kullan',
    'Use /create-rule': '/create-rule kullan',
    'Use /create-skill': '/create-skill kullan',
    'Use /create-subagent': '/create-subagent kullan',
    'Use /debug': '/debug kullan',
    'Use /in-cloud': '/in-cloud kullan',
    'Use /loop': '/loop kullan',
    'Use /model': '/model kullan',
    'Use /shell': '/shell kullan',
    'Use /review': '/review kullan',
    'Kullan /review': '/review kullan',
    'Use /plan': '/plan kullan',
    'Use /ask': '/ask kullan',
    'Use /canvas': '/canvas kullan',
    'Use /multitask': '/multitask kullan',
    'Use /simplify': '/simplify kullan',
    'Use /add-plugin': '/add-plugin kullan',
    'Use @browser to inspect page elements, view console logs, and analyze network traffic': '@browser ile sayfa öğelerini inceleyin, konsol günlüklerini görüntüleyin ve ağ trafiğini analiz edin',
    'to control and extend the agent loop with custom scripts': 'ile ajan döngüsünü özel betiklerle denetleyip genişletin',
    'to research your codebase before starting code changes': 'ile kod değişikliklerine başlamadan önce kod tabanınızı araştırın',
    'for an agentic code review of your changes': 'ile değişikliklerinizi ajan destekli kod incelemesinden geçirin',
    'to have Cursor find bugs, regressions, security issues, and missing tests': 'ile Cursor’un hataları, gerilemeleri, güvenlik sorunlarını ve eksik testleri bulmasını sağlayın',
    'Drag and drop agent chats to split your view into tiled panes': 'Görünümünüzü döşenmiş panellere bölmek için ajan sohbetlerini sürükleyip bırakın',
    'to triage PR comments, fix CI failures, and clear conflicts': 'ile PR yorumlarını önceliklendirin, CI hatalarını düzeltin ve çakışmaları temizleyin',
    'Use /babysit to triage PR comments, fix CI failures, and clear conflicts': '/babysit ile PR yorumlarını önceliklendirin, CI hatalarını düzeltin ve çakışmaları temizleyin',
    'Kullan /babysit to triage PR comments, fix CI failures, and clear conflicts': '/babysit ile PR yorumlarını önceliklendirin, CI hatalarını düzeltin ve çakışmaları temizleyin',
    'to improve agent execution with Plan Mode': 'ile Plan Modu’nu kullanarak ajan yürütmesini iyileştirin',
    'to have Cursor review all changed files for code quality and efficiency': 'ile Cursor’un tüm değişen dosyaları kod kalitesi ve verimlilik için incelemesini sağlayın',
    'so Cursor can work on your queued messages in parallel': 'ile Cursor’un sıradaki mesajlarınız üzerinde paralel çalışmasını sağlayın',
    ' so Cursor can work on your queued messages in parallel': ' ile Cursor’un sıradaki mesajlarınız üzerinde paralel çalışmasını sağlayın',
    'to turn your work into small, reviewable PRs': 'ile çalışmanızı küçük ve incelenebilir PR’lara bölün',
    'to get interactive visualizations like dashboards from Cursor': 'ile Cursor’dan pano gibi etkileşimli görselleştirmeler alın',
    'to create Cursor Automations without leaving your agent chat': 'ile ajan sohbetinden ayrılmadan Cursor Otomasyonları oluşturun',
    'to create Cursor Otomasyonları without leaving your agent chat': 'ile ajan sohbetinden ayrılmadan Cursor Otomasyonları oluşturun',
    'or /local to move agent sessions between runtimes': 'veya /local ile ajan oturumlarını çalışma ortamları arasında taşıyın',
    'to move agent sessions between runtimes': 'ile ajan oturumlarını çalışma ortamları arasında taşıyın',
    'to run agents remotely for better parallelization and durable execution': 'ile daha iyi paralelleştirme ve kalıcı yürütme için ajanları uzaktan çalıştırın',
    'to control agent behavior through system-level instructions': 'ile ajan davranışını sistem düzeyi talimatlarla denetleyin',
    'to customize Cursor for your workflows': 'ile Cursor’u iş akışlarınıza göre özelleştirin',
    'to set up specialized agents that Cursor can use to parallelize work': 'ile Cursor’un işi paralelleştirmek için kullanabileceği uzman ajanlar kurun',
    'to solve bugs that are hard to reproduce or understand': 'ile yeniden üretmesi veya anlaması zor hataları çözün',
    'to start a subagent in its own cloud VM, keeping your local workspace free': 'ile yerel çalışma alanınızı boş tutarak alt ajanı kendi bulut VM’inde başlatın',
    'to run a prompt on a schedule': 'ile bir istemi zamanlamaya göre çalıştırın',
    'to pick the best model for your task and select Composer for a great balance of cost vs. capability': 'ile göreviniz için en uygun modeli seçin; maliyet-yetenek dengesi için Composer’ı kullanın',
    'to run commands in the terminal': 'ile terminalde komut çalıştırın',
    'to run subagents to parallelize your requests instead of queuing them': 'ile isteklerinizi sıraya almak yerine paralel çalıştırmak için alt ajanları kullanın',
    'to inspect page elements, view console logs, and analyze network traffic': 'ile sayfa öğelerini inceleyin, konsol günlüklerini görüntüleyin ve ağ trafiğini analiz edin',
    'to install a plugin from the Cursor Marketplace': 'ile Cursor Eklenti Pazarı’ndan eklenti yükleyin',
    'to install a plugin from the Cursor Eklenti Pazarı': 'ile Cursor Eklenti Pazarı’ndan eklenti yükleyin',
    'lets you dictate better prompts for your agents': 'ajanlarınız için daha iyi istemleri dikte etmenizi sağlar',
    'uses read-only agents to research your codebase – hit shift+tab to get started': 'kod tabanınızı araştırmak için salt okunur ajanlar kullanır; başlamak için Shift+Tab tuşlarına basın',
    'improves agent outcomes and accuracy – hit shift+tab to get started': 'ajan sonuçlarını ve doğruluğunu iyileştirir; başlamak için Shift+Tab tuşlarına basın',
    'Search agents, files, actions...': 'Ajanları, dosyaları ve eylemleri ara...',
    'Search files...': 'Dosyalarda ara...',
    'Search actions...': 'Eylemlerde ara...',
    'Search Cursor settings...': 'Cursor ayarlarında ara...',
    'Search Cursor settings…': 'Cursor ayarlarında ara…',
    'Tool Call Density': 'Araç Çağrısı Yoğunluğu',
    'Theme': 'Tema',
    'Use automations to save time on repetitive tasks with always-on agents': 'Sürekli çalışan ajanlarla tekrarlı görevlerde zaman kazanmak için otomasyonları kullanın',
    'automations to save time on repetitive tasks with always-on agents': 'otomasyonlarla sürekli çalışan ajanlarda tekrarlı görevlerde zaman kazanın',
    'Recent Workspaces': 'Son Çalışma Alanları',
    'Tell Cursor to use subagents to break down tasks, do work in parallel, and preserve context': 'Cursor’a görevleri bölmek, paralel çalışmak ve bağlamı korumak için alt ajanları kullanmasını söyleyin',
    'Select Composer in your model picker for a great balance of intelligence and cost': 'Zeka ve maliyet arasında iyi denge için model seçicide Composer’ı seçin',
    'Seç Composer in your model picker for a great balance of intelligence and cost': 'Zeka ve maliyet arasında iyi denge için model seçicide Composer’ı seçin',
    'Composer in your model picker for a great balance of intelligence and cost': 'model seçicide Composer’ı seçin; zeka ve maliyet arasında iyi denge sağlar',
    'in your model picker for a great balance of intelligence and cost': 'model seçicide; zeka ve maliyet arasında iyi denge sağlar',
    'Actions': 'Eylemler',
    'Dictate': 'Dikte Et',
    'Mode': 'Mod',
    'Agent Mode': 'Ajan Modu',
    'Debug Mode': 'Hata Ayıklama Modu',
    'Select': 'Seç',
    'Change Filter': 'Filtreyi Değiştir',
    'Configure Display Language': 'Görüntüleme Dilini Yapılandır',
    'Previous Tab': 'Önceki Sekme',
    'Toggle Design Mode': 'Tasarım Modunu Aç/Kapat',
    'Toggle Full Screen': 'Tam Ekranı Aç/Kapat',
    'Toggle Git Blame': "Git Blame'i Aç/Kapat",
    'Review Changes': 'Değişiklikleri İncele',
    'Light Theme': 'Açık Tema',
    'Dark Theme': 'Koyu Tema',
    'System Theme': 'Sistem Teması',
    'High Contrast Theme': 'Yüksek Karşıtlık Teması',
    'Developer': 'Geliştirici',
    'Reload Window': 'Pencereyi Yeniden Yükle',
    'Developer: Open Logs Folder': 'Geliştirici: Günlükler Klasörünü Aç',
    'Start Extension Host CPU Profiler': 'Eklenti Ana Makinesi CPU Profilleyicisini Başlat',
    'Start Extension Host Heap Allocation Profiler': 'Eklenti Ana Makinesi Heap Ayırma Profilleyicisini Başlat',
    'Start Remote Server CPU Profiler': 'Uzak Sunucu CPU Profilleyicisini Başlat',
    'Process Explorer': 'İşlem Gezgini',
    'Start Electron Trace': 'Electron İzlemeyi Başlat',
    'Developer: Delete Old Chats...': 'Geliştirici: Eski Sohbetleri Sil...',
    'GC Agent KV Blobs': 'GC Ajan KV Blobları',
    'Workspace Diagnostics': 'Çalışma Alanı Tanılamaları',
    'Display Workspace Metadata': 'Çalışma Alanı Meta Verilerini Göster',
    'Display Explorer Orchestrator Cache': 'Gezgin Orkestratör Önbelleğini Göster',
    'Workspace': 'Çalışma Alanı',
    'Connect via WSL': 'WSL ile Bağlan',
    "Reset choice for 'File operation needs preview'": "'Dosya işlemi için önizleme gerekiyor' seçimini sıfırla",
    'Comments: Go to Next Commented Range': 'Yorumlar: Sonraki Yorumlu Aralığa Git',
    'Add User Rule': 'Kullanıcı Kuralı Ekle',
    'Add Data Breakpoint at Address': 'Adrese Veri Kesme Noktası Ekle',
    'Open Agent Changes': 'Ajan Değişikliklerini Aç',
    'Start Agent Review': 'Ajan İncelemesini Başlat',
    'Clone Repository': 'Depoyu Klonla',
    'Connect': 'Bağlan',
    'Code Intelligence': 'Kod Zekası',
    'Cursor Tab': 'Cursor Sekmesi',
    'Tab Stats': 'Sekme İstatistikleri',
    'Agent Stats': 'Ajan İstatistikleri',
    'Agent AI Stats (Today)': 'Ajan AI İstatistikleri (Bugün)',
    'Results': 'Sonuçlar',
    'New agent': 'Yeni ajan',
}

NLS_REQUIRED = {
    'Installing': 'Yükleniyor',
    'Resolving shell environment...': 'Kabuk ortamı çözümleniyor...',
    'Comma-separated list of Cursor organization ids whose members are allowed to sign in on this device (set via device management).': 'Bu cihazda oturum açmasına izin verilen üyelerin Cursor kuruluş kimliklerinin virgülle ayrılmış listesi (cihaz yönetimiyle ayarlanır).',
    'Comma-separated list of Cursor team ids whose members are allowed to sign in on this device (set via device management). Supersedes the singular AllowedTeamId policy; both are honored.': 'Bu cihazda oturum açmasına izin verilen üyelerin Cursor ekip kimliklerinin virgülle ayrılmış listesi (cihaz yönetimiyle ayarlanır). Tekil AllowedTeamId ilkesinin yerini alır; her ikisi de geçerlidir.',
    'Comma-separated list of email domains (e.g. example.com) whose accounts are allowed to sign in on this device (set via device management). Exact domain match only; subdomains are not implicitly included.': 'Bu cihazda oturum açmasına izin verilen hesapların e-posta alan adlarının virgülle ayrılmış listesi (ör. example.com; cihaz yönetimiyle ayarlanır). Yalnızca tam alan adı eşleşir; alt alan adları kendiliğinden dahil edilmez.',
    'Comma-separated list of exact account emails allowed to sign in on this device (set via device management). Compared case-insensitively.': 'Bu cihazda oturum açmasına izin verilen hesap e-posta adreslerinin virgülle ayrılmış tam listesi (cihaz yönetimiyle ayarlanır). Büyük/küçük harf ayrımı yapılmaz.',
    'Skill Publishing': 'Beceri Yayınlama',
    "When enabled via device management (MDM), Cursor's backend refuses to issue or refresh sign-in sessions for accounts that match none of the configured allowed organizations, teams, emails, or email domains.": 'Cihaz yönetimi (MDM) üzerinden etkinleştirildiğinde Cursor altyapısı; izin verilen kuruluş, ekip, e-posta veya e-posta alan adlarından hiçbiriyle eşleşmeyen hesaplar için oturum oluşturmayı ya da yenilemeyi reddeder.',
}

RAW_REPLACEMENTS = {
    'q?"Search Cursor settings\\\\u2026"': 'q?"Cursor ayarlarında ara\\\\u2026"',
    '\'New agent: "': '\'Yeni ajan: "',
}

PROPS = ('label', 'title', 'placeholder', 'tooltip', 'heading', 'header', 'subtitle',
         'emptyMessage', 'buttonLabel', 'primaryButtonLabel', 'secondaryButtonLabel',
         'confirmLabel', 'cancelLabel', 'okLabel', 'message', 'detail', 'children',
         'text', 'ariaLabel', 'description', 'inlineLabel', 'qualifierSuffix')

alternatives = '|'.join(sorted((re.escape(k) for k in MAP), key=len, reverse=True))
visible_re = re.compile(
    r'((?:"aria-label"|' + '|'.join(PROPS) + r'):)(["\'])(' + alternatives + r')\2'
)

if __name__ == '__main__':
    total = 0
    for fname in FILES:
        if not __import__('os').path.exists(fname):
            continue
        text = io.open(fname, encoding='utf-8').read()
        text, changed = visible_re.subn(
            lambda m: m.group(1) + m.group(2) + MAP[m.group(3)] + m.group(2), text
        )
        for source, translated in DIRECT_MAP.items():
            for quote in ('"', "'"):
                old = quote + source + quote
                new = quote + translated + quote
                count = text.count(old)
                if count:
                    text = text.replace(old, new)
                    changed += count
        for old, new in RAW_REPLACEMENTS.items():
            count = text.count(old)
            if count:
                text = text.replace(old, new)
                changed += count
        # Low/Medium/High bazı minify edilmiş TypeScript enum tablolarında
        # program mantığıdır. Görünür etiket çevirisi bu ters eşlemelere
        # sızdıysa özgün enum adlarını geri yükle; aksi halde model menüsünde
        # seçim yapmak Electron penceresini kilitleyebilir.
        enum_pattern = re.compile(
            r'(\b([A-Za-z_$][\w$]*)\[\2\.(Low|Medium|High)=\d+\]=)'
            r'"(?:Düşük|Orta|Yüksek)"'
        )
        text, enum_repairs = enum_pattern.subn(
            lambda m: m.group(1) + '"' + m.group(3) + '"', text
        )
        changed += enum_repairs
        io.open(fname, 'w', encoding='utf-8', newline='').write(text)
        total += changed
        print('%s: %d kalan UI metni cevrildi' % (fname, changed))
    print('Toplam: %d' % total)
