# -*- coding: utf-8 -*-
# Cursor Ayarlari satirlari (label/description ciftleri) + Connect butonu + kalan basliklar.
import io

pairs = [
 ("Marketplace Access", "Select who can see and use plugins from this team marketplace",
  "Market Erişimi", "Bu ekip marketindeki eklentileri kimlerin görüp kullanabileceğini seçin"),
 ("Enable Auto Refresh", "Automatically update plugins when changes are pushed to the repository",
  "Otomatik Yenilemeyi Etkinleştir", "Depoya değişiklik gönderildiğinde eklentileri otomatik güncelle"),
 ("Serve Marketplace From Cursor", "Cursor keeps a synced copy of this repository and serves plugins from it, so team members can use the marketplace without GitHub access to the source repo. Access is controlled by Marketplace Access.",
  "Marketi Cursor'dan Sun", "Cursor bu deponun eşitlenmiş bir kopyasını tutar ve eklentileri oradan sunar; böylece ekip üyeleri kaynak depoya GitHub erişimi olmadan marketi kullanabilir. Erişim, Market Erişimi ile denetlenir."),
 ("Plugin Repository", "Fetch marketplace plugins from the GitHub repository",
  "Eklenti Deposu", "Market eklentilerini GitHub deposundan getir"),
 ("Remove Marketplace", "This marketplace and its access settings will be removed. The source repository won't be affected.",
  "Marketi Kaldır", "Bu market ve erişim ayarları kaldırılacak. Kaynak depo etkilenmeyecek."),
 ("All Tasks", "Everything on the board", "Tüm Görevler", "Panodaki her şey"),
 ("Working", "Ready with dependencies satisfied", "Çalışılıyor", "Bağımlılıkları karşılanmış, hazır"),
 ("Blocked", "Waiting on a dependency or cycle", "Engellendi", "Bir bağımlılık veya döngü bekleniyor"),
 ("Commit changes", "Create a checkpoint commit with your current changes",
  "Değişiklikleri commit'le", "Geçerli değişikliklerinizle bir denetim noktası commit'i oluşturun"),
 ("Stash changes", "Save your changes to a stash and restore them later",
  "Değişiklikleri zulala", "Değişikliklerinizi bir zulaya kaydedin ve daha sonra geri yükleyin"),
 ("Discard changes", "Delete your current uncommitted changes before switching",
  "Değişiklikleri at", "Geçiş yapmadan önce commit edilmemiş geçerli değişikliklerinizi silin"),
 ("Canvas", "Produces canvases", "Canvas", "Canvas üretir"),
 ("Stash changes", "Temporarily save uncommitted work, then check out the cloud agent branch.",
  "Değişiklikleri zulala", "Commit edilmemiş işi geçici olarak kaydedin, sonra bulut ajanı dalına geçin."),
 ("Commit changes", "Create a checkpoint commit of your changes, then check out the branch.",
  "Değişiklikleri commit'le", "Değişikliklerinizin denetim noktası commit'ini oluşturun, sonra dala geçin."),
 ("New MCP Configuration", "Creates a new MCP configuration with example servers",
  "Yeni MCP Yapılandırması", "Örnek sunucularla yeni bir MCP yapılandırması oluşturur"),
 ("Stash Changes", "Save changes to a stash and restore them later",
  "Değişiklikleri Zulala", "Değişiklikleri bir zulaya kaydedin ve daha sonra geri yükleyin"),
 ("Commit Changes", "Create a checkpoint commit with your current changes",
  "Değişiklikleri Commit'le", "Geçerli değişikliklerinizle bir denetim noktası commit'i oluşturun"),
 ("Discard Changes", "Permanently discard your current changes before switching branches",
  "Değişiklikleri At", "Dal değiştirmeden önce geçerli değişikliklerinizi kalıcı olarak atın"),
 ("Cancel", "Cancel the checkout operation", "İptal", "Dala geçiş işlemini iptal et"),
 ("Development", "Use development environment", "Geliştirme", "Geliştirme ortamını kullan"),
 ("Production", "Use production environment", "Üretim", "Üretim ortamını kullan"),
 ("Full Local", "Use full local environment (non-VM running locally)",
  "Tam Yerel", "Tam yerel ortamı kullan (yerelde çalışan, VM olmayan)"),
 ("Manage Settings", "Connect GitHub/GitLab, manage team and user settings, and configure environments",
  "Ayarları Yönet", "GitHub/GitLab'ı bağlayın, ekip ve kullanıcı ayarlarını yönetin, ortamları yapılandırın"),
 ("Connect Slack", "Work with Cloud Agents from Slack",
  "Slack'i Bağla", "Bulut Ajanlarıyla Slack üzerinden çalışın"),
 ("Dedicated Agent Runtime", "Run Private Inference in a separate local process to isolate it from remote workspace activity. Reload Cursor after changing this setting.",
  "Ayrılmış Ajan Çalışma Zamanı", "Özel Çıkarımı uzak çalışma alanı etkinliğinden yalıtmak için ayrı bir yerel işlemde çalıştırın. Bu ayarı değiştirdikten sonra Cursor'ı yeniden yükleyin."),
 ("Import Claude Code Agents", "Bring your Claude Code sessions into Cursor.",
  "Claude Code Ajanlarını İçe Aktar", "Claude Code oturumlarınızı Cursor'a taşıyın."),
 ("HTTP Compatibility Mode", "HTTP/2 is recommended for low-latency streaming. In some corporate proxy and VPN environments, the compatibility mode may need to be lowered.",
  "HTTP Uyumluluk Modu", "Düşük gecikmeli akış için HTTP/2 önerilir. Bazı kurumsal proxy ve VPN ortamlarında uyumluluk modunun düşürülmesi gerekebilir."),
 ("Required Domains", "These domains must be accessible for Cursor to function. Add them to your firewall or proxy allowlist.",
  "Gerekli Etki Alanları", "Cursor'ın çalışması için bu etki alanlarına erişilebilmelidir. Bunları güvenlik duvarı veya proxy izin listenize ekleyin."),
 ("Network Diagnostics", "Check network connectivity to all Cursor services",
  "Ağ Tanılamaları", "Tüm Cursor hizmetlerine ağ bağlantısını denetle"),
 ("Cursor Tab", "Context-aware, multi-line suggestions around your cursor based on recent edits",
  "Cursor Tab", "Son düzenlemelere dayalı, imlecinizin çevresinde bağlama duyarlı, çok satırlı öneriler"),
 ("Suggestions While Commenting", "Allow Tab to trigger while in a comment region",
  "Açıklama Yazarken Öneriler", "Tab'ın açıklama bölgesindeyken tetiklenmesine izin ver"),
 ("Whitespace-Only Suggestions", "Suggest edits like new lines and indentation that modify whitespace only",
  "Yalnızca Boşluk Önerileri", "Yalnızca boşlukları değiştiren yeni satır ve girinti gibi düzenlemeler öner"),
 ("Ignored Files", "Glob patterns for files where Cursor Tab will not suggest",
  "Yoksayılan Dosyalar", "Cursor Tab'ın öneri yapmayacağı dosyalar için glob desenleri"),
 ("Code Block Word Wrap", "Wrap long lines in Agent conversation code blocks",
  "Kod Bloklarında Sözcük Kaydırma", "Ajan konuşmalarındaki kod bloklarında uzun satırları kaydır"),
 ("Themed Diff Backgrounds", "Satır içi kod farkları için temalı arka plan renkleri kullan",
  "Temalı Fark Arka Planları", "Satır içi kod farkları için temalı arka plan renkleri kullan"),
 ("Text Size", "Adjust the conversation text size", "Metin Boyutu", "Konuşma metni boyutunu ayarlayın"),
 ("Max Tab Count", "Limit how many chat tabs can be open at once",
  "En Fazla Sekme Sayısı", "Aynı anda açık olabilecek sohbet sekmesi sayısını sınırlayın"),
 ("Default Environment", "Where new agents start by default",
  "Varsayılan Ortam", "Yeni ajanların varsayılan olarak başlayacağı yer"),
 ("Queue Messages", "Adjust the default behavior of sending a message while Agent is running",
  "Mesajları Sıraya Al", "Ajan çalışırken mesaj gönderme davranışını ayarlayın"),
 ("Usage Summary", "When to show the usage summary at the bottom of the chat pane",
  "Kullanım Özeti", "Sohbet panelinin altında kullanım özetinin ne zaman gösterileceğini seçin"),
 ("Agent Autocomplete", "Contextual suggestions while prompting Agent",
  "Ajan Otomatik Tamamlama", "Ajana istem yazarken bağlamsal öneriler gösterin"),
 ("Follow-Up Prompt Suggestions", "Suggest a follow-up for the Agent",
  "Devam İstemi Önerileri", "Ajan için bir devam istemi öner"),
 ("Auto-Approve Mode Transitions", "Allow Agent to switch modes without asking first, such as Agent to Plan or Agent to Debug. When off, Cursor asks before switching.",
  "Mod Geçişlerini Otomatik Onayla", "Ajanın önceden sormadan Ajan, Plan veya Hata Ayıklama gibi modlar arasında geçmesine izin verin. Kapalıyken Cursor geçişten önce sorar."),
 ("Voice Submit Keywords", "Custom words that submit a voice prompt. Spaces and punctuation are ignored.",
  "Sesli Gönderme Anahtar Sözcükleri", "Sesli istemi gönderen özel sözcükler. Boşluklar ve noktalama işaretleri yok sayılır."),
 ("Compact Terminal Tool Calls", "Show terminal commands in compact view by default",
  "Kompakt Terminal Araç Çağrıları", "Terminal komutlarını varsayılan olarak kompakt görünümde göster"),
 ("Include Third-Party Plugins, Skills, and Other Configs", "Automatically import agent configs from other tools",
  "Üçüncü Taraf Eklentileri, Becerileri ve Diğer Yapılandırmaları Dahil Et", "Diğer araçlardaki ajan yapılandırmalarını otomatik içe aktar"),
 ("Keep This Computer Awake", "Prevent sleep when this computer is plugged in and Remote Control is enabled",
  "Bu Bilgisayarı Uyanık Tut", "Bilgisayar prize takılıyken ve Uzaktan Denetim etkinken uykuya geçmesini önleyin"),
 ("Inline Diffs", "Show inline diff decorations in the editor instead of only showing changes in the review panel",
  "Satır İçi Farklar", "Değişiklikleri yalnızca inceleme panelinde göstermek yerine düzenleyicide satır içi fark süslemeleri göster"),
 ("Auto Format on Agent Finish", "Automatically format files when the agent finishes",
  "Ajan Bitirdiğinde Otomatik Biçimlendir", "Ajan bitirdiğinde dosyaları otomatik olarak biçimlendir"),
 ("Legacy Terminal Tool", "Use the legacy terminal tool in agent mode, for use on systems with unsupported shell configurations",
  "Eski Terminal Aracı", "Desteklenmeyen kabuk yapılandırmalarına sahip sistemlerde kullanmak için ajan modunda eski terminal aracını kullan"),
 ("Toolbar on Selection", "Show Add to Chat & Quick Edit buttons when selecting code",
  "Seçimde Araç Çubuğu", "Kod seçerken Sohbete Ekle ve Hızlı Düzenle düğmelerini göster"),
 ("Enable LSPs", "Enable language server by default to provide code intelligence in workspaces",
  "LSP'leri Etkinleştir", "Çalışma alanlarında kod zekası sağlamak için dil sunucusunu varsayılan olarak etkinleştir"),
 ("Enable LSPs for Worktrees", "Enable language server by default to provide code intelligence in agent worktree workspaces",
  "Çalışma Ağaçları İçin LSP'leri Etkinleştir", "Ajan çalışma ağacı çalışma alanlarında kod zekası sağlamak için dil sunucusunu varsayılan olarak etkinleştir"),
 ("Maximum Local LSP Workspaces", "Maximum local workspaces that can run language servers at the same time",
  "En Fazla Yerel LSP Çalışma Alanı", "Aynı anda dil sunucusu çalıştırabilecek en fazla yerel çalışma alanı"),
 ("Maximum Remote LSP Workspaces", "Maximum remote workspaces that can run language servers at the same time",
  "En Fazla Uzak LSP Çalışma Alanı", "Aynı anda dil sunucusu çalıştırabilecek en fazla uzak çalışma alanı"),
 ("Auto-Run Network Access", "Control which network requests are allowed when commands run in the sandbox. Edit allowed/denied domains in sandbox.json in your workspace.",
  "Otomatik Çalıştırma Ağ Erişimi", "Komutlar korumalı alanda çalışırken hangi ağ isteklerine izin verileceğini denetleyin. İzin verilen/reddedilen etki alanlarını çalışma alanınızdaki sandbox.json içinde düzenleyin."),
 ("Smart Allowlist", "Use AI-powered command classification to intelligently match commands against allowlist patterns and suggest sandbox modes",
  "Akıllı İzin Listesi", "Komutları izin listesi desenleriyle akıllıca eşleştirmek ve korumalı alan modları önermek için yapay zeka destekli komut sınıflandırması kullan"),
 ("Allowlist Options", "You can configure Shell, MCP and Fetch allowlists for Auto mode. However, Auto works well without these.",
  "İzin Listesi Seçenekleri", "Otomatik mod için Kabuk, MCP ve Getirme izin listeleri yapılandırabilirsiniz. Ancak Otomatik, bunlar olmadan da iyi çalışır."),
 ("Start Agent Review on Commit", "Automatically review your changes for issues after each commit",
  "Commit'te Ajan İncelemesini Başlat", "Her commit'ten sonra değişikliklerinizi sorunlara karşı otomatik incele"),
 ("Auto-Run on Agent Finish", "Automatically run Review when Agent finishes and has made file changes",
  "Ajan Bitirdiğinde Otomatik Çalıştır", "Ajan bitirdiğinde ve dosya değişiklikleri yaptığında İncelemeyi otomatik çalıştır"),
 ("Include Submodules in Agent Review", "Include changes from Git submodules in the review",
  "Ajan İncelemesine Alt Modülleri Dahil Et", "Git alt modüllerindeki değişiklikleri incelemeye dahil et"),
 ("Include Untracked Files in Agent Review", "Include untracked files (new files not yet added to Git) in the review",
  "Ajan İncelemesine İzlenmeyen Dosyaları Dahil Et", "İzlenmeyen dosyaları (henüz Git'e eklenmemiş yeni dosyalar) incelemeye dahil et"),
 ("Default Approach", "Choose between quick or more thorough, higher-cost analysis",
  "Varsayılan Yaklaşım", "Hızlı ya da daha kapsamlı, daha yüksek maliyetli analiz arasında seçim yapın"),
 ("Fetch Domain Allowlist", "Domains that Agent can fetch from automatically. Use '*' for all domains, '*.example.com' for wildcard subdomains.",
  "Getirme Etki Alanı İzin Listesi", "Ajanın otomatik olarak veri getirebileceği etki alanları. Tüm etki alanları için '*', joker alt etki alanları için '*.example.com' kullanın."),
 ("Completion Sound", "Play a sound when Agent finishes responding",
  "Tamamlanma Sesi", "Ajan yanıtını bitirdiğinde bir ses çal"),
 ("Sign In", "Sign in to get started with Cursor's AI features",
  "Oturum Aç", "Cursor'ın yapay zeka özelliklerini kullanmaya başlamak için oturum açın"),
 ("Cursor Account", "Manage your account and billing",
  "Cursor Hesabı", "Hesabınızı ve faturalandırmanızı yönetin"),
 ("Invite Team Members", "Accelerate development, shared knowledge, and context across your team",
  "Ekip Üyelerini Davet Et", "Ekibinizde geliştirmeyi, ortak bilgiyi ve bağlamı hızlandırın"),
 ("Editor Settings", "Configure font, formatting, minimap and more",
  "Düzenleyici Ayarları", "Yazı tipini, biçimlendirmeyi, mini haritayı ve daha fazlasını yapılandırın"),
 ("Keyboard Shortcuts", "Configure keyboard shortcuts",
  "Klavye Kısayolları", "Klavye kısayollarını yapılandırın"),
 ("Import Settings from VS Code", "Import settings, extensions, and keybindings from VS Code",
  "VS Code'dan Ayarları İçe Aktar", "VS Code'dan ayarları, uzantıları ve tuş bağlamalarını içe aktarın"),
 ("Conversation Density", "Choose how much detail Agent tool calls show in the conversation",
  "Konuşma Yoğunluğu", "Ajan araç çağrılarının konuşmada ne kadar ayrıntı göstereceğini seçin"),
 ("Title Bar", "Show title bar in agent layout", "Başlık Çubuğu", "Ajan düzeninde başlık çubuğunu göster"),
 ("Status Bar", "Show status bar at the bottom of the window",
  "Durum Çubuğu", "Pencerenin altında durum çubuğunu göster"),
 ("Review Control Location", "Show inline diff review controls in top level breadcrumbs or floating island",
  "İnceleme Denetimi Konumu", "Satır içi fark inceleme denetimlerini üst düzey içerik haritasında veya yüzen adada göster"),
 ("Auto-Hide Editor When Empty", "When all editors are closed, hide the editor area and maximize chat",
  "Boşken Düzenleyiciyi Otomatik Gizle", "Tüm düzenleyiciler kapatıldığında düzenleyici alanını gizle ve sohbeti büyüt"),
 ("Tips", "Show rotating tips on the empty screen", "İpuçları", "Boş ekranda dönen ipuçları göster"),
 ("Window Restoration", "Controls which windows Cursor restores on startup",
  "Pencere Geri Yükleme", "Cursor'ın başlangıçta hangi pencereleri geri yükleyeceğini denetler"),
 ("System Notifications", "Show system notifications when Agent completes or needs attention",
  "Sistem Bildirimleri", "Ajan tamamlandığında veya ilgi gerektiğinde sistem bildirimleri göster"),
 ("Warning Notifications", "Show warning-level in-app toasts",
  "Uyarı Bildirimleri", "Uyarı düzeyinde uygulama içi bildirimler göster"),
 ("Branch Prefix", "Prefix for new branches created by Agent (e.g., cursor/, username/)",
  "Dal Öneki", "Ajanın oluşturduğu yeni dallar için önek (örn. cursor/, kullaniciadi/)"),
 ("Team-Level Repository Control", "Disable AI features in specific repositories based on file pattern",
  "Ekip Düzeyinde Depo Denetimi", "Dosya desenine göre belirli depolarda yapay zeka özelliklerini devre dışı bırak"),
 ("Wait for MCP Authentication", "Wait indefinitely to authenticate when prompted. When off, skip authentication prompts after 30 seconds.",
  "MCP Kimlik Doğrulamasını Bekle", "İstendiğinde kimlik doğrulaması için süresiz bekle. Kapalıyken kimlik doğrulama istemleri 30 saniye sonra atlanır."),
 ("Explore Subagent Model", "Choose the model used by the Explore subagent for initial research",
  "Keşif Alt Ajanı Modeli", "İlk araştırma için Keşif alt ajanının kullanacağı modeli seçin"),
 ("Base URL", "OpenAI-compatible API base URL for the local agent.",
  "Temel URL", "Yerel ajan için OpenAI uyumlu API temel URL'si."),
 ("API Key", "API key used for requests to your gateway.",
  "API Anahtarı", "Ağ geçidinize yapılan istekler için kullanılan API anahtarı."),
 ("Override OpenAI Base URL", "Change the base URL for OpenAI API requests.",
  "OpenAI Temel URL'sini Geçersiz Kıl", "OpenAI API istekleri için temel URL'yi değiştirin."),
 ("On-Demand Usage", "Enable on-demand usage to go beyond your plan's included usage. Requires a paid plan.",
  "İsteğe Bağlı Kullanım", "Planınıza dahil kullanımın ötesine geçmek için isteğe bağlı kullanımı etkinleştirin. Ücretli plan gerektirir."),
 ("Monthly Limit", "Set a fixed amount or make it unlimited.",
  "Aylık Sınır", "Sabit bir tutar belirleyin veya sınırsız yapın."),
 ("Monthly Limit", "Set a fixed amount or make on-demand usage unlimited",
  "Aylık Sınır", "Sabit bir tutar belirleyin veya isteğe bağlı kullanımı sınırsız yapın"),
 ("Auto-Approve Mode Transitions", "Allow Agent to switch modes without asking first",
  "Mod Geçişlerini Otomatik Onayla", "Ajanın önceden sormadan mod değiştirmesine izin ver"),
 ("Web Search Tool", "Allow Agent to search the web for relevant information",
  "Web Arama Aracı", "Ajanın ilgili bilgiler için web'de arama yapmasına izin ver"),
 ("Legacy Terminal Tool", "Use legacy terminal tool on unsupported shells",
  "Eski Terminal Aracı", "Desteklenmeyen kabuklarda eski terminal aracını kullan"),
 ("Auto-Parse Links", "Automatically parse links pasted into Quick Edit",
  "Bağlantıları Otomatik Ayrıştır", "Hızlı Düzenle'ye yapıştırılan bağlantıları otomatik ayrıştır"),
 ("Explore Subagent Model", "Choose the model used by Explore subagent for initial research",
  "Keşif Alt Ajanı Modeli", "İlk araştırma için Keşif alt ajanının kullanacağı modeli seçin"),
 ("Branch Prefix", "Prefix for new Agent branches", "Dal Öneki", "Yeni Ajan dalları için önek"),
 ("Wait for MCP Authentication", "Wait indefinitely; otherwise skip prompts after 30 seconds",
  "MCP Kimlik Doğrulamasını Bekle", "Süresiz bekle; aksi halde istemler 30 saniye sonra atlanır"),
 ("Index New Folders", "Automatically index small new folders",
  "Yeni Klasörleri Dizinle", "Küçük yeni klasörleri otomatik dizinle"),
 ("Hierarchical Cursor Ignore", "Apply .cursorignore files to subdirectories",
  "Hiyerarşik Cursor Yoksayması", ".cursorignore dosyalarını alt dizinlere uygula"),
 ("Ignore Symlinks in Cursor Ignore Search", "Skip symlinks during discovery",
  "Cursor Yoksayma Aramasında Sembolik Bağlantıları Yoksay", "Keşif sırasında sembolik bağlantıları atla"),
 ("HTTP Compatibility Mode", "Configure HTTP compatibility for proxies and VPNs",
  "HTTP Uyumluluk Modu", "Proxy'ler ve VPN'ler için HTTP uyumluluğunu yapılandırın"),
 ("Required Domains", "Domains required for Cursor", "Gerekli Etki Alanları", "Cursor için gerekli etki alanları"),
 ("Network Diagnostics", "Check connectivity to all Cursor services",
  "Ağ Tanılamaları", "Tüm Cursor hizmetlerine bağlantıyı denetle"),
 ("Agent Layout", "Focus on Agent chats", "Ajan Düzeni", "Ajan sohbetlerine odaklan"),
 ("IDE Layout", "Focus on files", "IDE Düzeni", "Dosyalara odaklan"),
 ("Ignore branch difference", "Proceed anyway (changes might not apply correctly)",
  "Dal farkını yoksay", "Yine de devam et (değişiklikler doğru uygulanmayabilir)"),
 ("Cancel", "Abort the operation", "İptal", "İşlemi durdur"),
 ("Stash changes", "Save your changes and restore them later",
  "Değişiklikleri zulala", "Değişikliklerinizi kaydedin ve daha sonra geri yükleyin"),
 ("Always Apply", "Apply to every chat and cmd-k session",
  "Her Zaman Uygula", "Her sohbete ve cmd-k oturumuna uygula"),
 ("Apply Intelligently", "When Agent decides it's relevant based on description",
  "Akıllıca Uygula", "Ajan, açıklamaya göre ilgili olduğuna karar verdiğinde"),
 ("Apply to Specific Files", "When file matches a specified pattern",
  "Belirli Dosyalara Uygula", "Dosya belirtilen bir desenle eşleştiğinde"),
 ("Apply Manually", "When @-mentioned", "El İle Uygula", "@ ile anıldığında"),
 ("Remote Host", "Runs in the remote extension host for this workspace.",
  "Uzak Ana Bilgisayar", "Bu çalışma alanı için uzak uzantı ana bilgisayarında çalışır."),
 ("Conflicts with base", "Merge blocked: conflicts with base",
  "Temel ile çakışıyor", "Birleştirme engellendi: temel ile çakışmalar var"),
 ("Status checks failing", "Merge blocked: required status checks are failing",
  "Durum denetimleri başarısız", "Birleştirme engellendi: gerekli durum denetimleri başarısız"),
 ("Checks still running", "Merge blocked: required status checks are still running",
  "Denetimler hâlâ çalışıyor", "Birleştirme engellendi: gerekli durum denetimleri hâlâ çalışıyor"),
 ("Blocked by branch rules", "Merging is blocked by branch protection rules",
  "Dal kuralları engelliyor", "Birleştirme, dal koruma kuralları tarafından engelleniyor"),
 ("Merge status pending", "Merge status is being determined...",
  "Birleştirme durumu bekleniyor", "Birleştirme durumu belirleniyor..."),
 ("Merge status pending", "Merge status is being calculated. Refresh if it does not resolve.",
  "Birleştirme durumu bekleniyor", "Birleştirme durumu hesaplanıyor. Çözülmezse yenileyin."),
 ("Cannot be merged", "This pull request cannot be merged",
  "Birleştirilemez", "Bu pull request birleştirilemez"),
 ("$20/ay", "$20 usage credits", "$20/ay", "$20 kullanım kredisi"),
 ("$60/ay", "$70 usage credits", "$60/ay", "$70 kullanım kredisi"),
 ("$200/mo", "$400 usage credits", "$200/ay", "$400 kullanım kredisi"),
 ("Ask Every Time", "Suggest tasks to be accepted",
  "Her Zaman Sor", "Görevleri onaya sunarak öner"),
 ("Run Autonomously", "Drive the PR end-to-end",
  "Otonom Çalış", "PR'ı uçtan uca yürüt"),
]

# title: kalibindaki kalanlar
title_pairs = [
 ("Search", "Codebase, web", "Ara", "Kod tabanı, web"),
 ("Edit", "Files in workspace", "Düzenle", "Çalışma alanındaki dosyalar"),
 ("Run", "Commands", "Çalıştır", "Komutlar"),
 ("Clear Browsing History", None, "Gezinme Geçmişini Temizle", None),
 ("Clear Cookies", None, "Tanımlama Bilgilerini Temizle", None),
 ("Clear Cache", None, "Önbelleği Temizle", None),
 ("Clear Accepted Certificates", None, "Kabul Edilen Sertifikaları Temizle", None),
 ("Disable HTTP/1.1 SSE", None, "HTTP/1.1 SSE'yi Devre Dışı Bırak", None),
]

# Connect butonu (tutarli baglamli degisimler; RPC method name'e dokunma)
connect = [
 ('?"Connect":"Add"', '?"Bağlan":"Ekle"'),
 ('==="Connect")', '==="Bağlan")'),
 ('"Reconnect":"Connect"', '"Yeniden Bağlan":"Bağlan"'),
 ('"idle"?"Connect":', '"idle"?"Bağlan":'),
 ('"Connecting...":"Connect"', '"Bağlanıyor...":"Bağlan"'),
 ('children:"Connect"', 'children:"Bağlan"'),
 ('?I?"Connect":"Save"', '?I?"Bağlan":"Kaydet"'),
 ('title:{value:"Connect Slack",original:"Connect Slack"}', 'title:{value:"Slack\'i Bağla",original:"Connect Slack"}'),
]

for fname in ["workbench.desktop.main.js", "workbench.glass.main.js"]:
    s = io.open(fname, encoding="utf-8").read()
    total = 0
    for t, d, t2, d2 in pairs:
        old = 'label:"%s",description:"%s"' % (t, d)
        new = 'label:"%s",description:"%s"' % (t2, d2)
        c = s.count(old)
        if c:
            s = s.replace(old, new)
            total += c
    for t, d, t2, d2 in title_pairs:
        if d is None:
            old = 'title:"%s"' % t
            new = 'title:"%s"' % t2
        else:
            old = 'title:"%s",description:"%s"' % (t, d)
            new = 'title:"%s",description:"%s"' % (t2, d2)
        c = s.count(old)
        if c:
            s = s.replace(old, new)
            total += c
    for a, b in connect:
        c = s.count(a)
        if c:
            s = s.replace(a, b)
            total += c
    io.open(fname, "w", encoding="utf-8", newline="").write(s)
    print(fname, "degisim:", total)
